In [441]:
import pandas as pd
import numpy as np
url1 = "https://raw.githubusercontent.com/TimoLischke/Data-wrangling-project-Nico-Timo_new/refs/heads/main/CancerDeathsbyCountryandTypeDataset.csv"
df = pd.read_csv(url1)
#path = r"C:\Users\admin\Documents\GitHub\Data-wrangling-project-Nico-Timo\CancerDeathsbyCountryandTypeDataset.csv"
#df = pd.read_csv(path)
df

,Country,Code,Year,Liver cancer,Kidney cancer,Larynx cancer,Breast cancer,Thyroid cancer,Stomach cancer,Bladder cancer,...,Non-melanoma skin cancer,Lip and oral cavity cancer,Brain and nervous system cancer,"Tracheal, bronchus, and lung cancer",Gallbladder and biliary tract cancer,Malignant skin melanoma,Leukemia,Hodgkin lymphoma,Multiple myeloma,Other cancers
0,Afghanistan,AFG,1990,243.663716,39.470495,109.334207,766.535431,79.820167,923.495208,148.139204,...,26.446156,53.599636,163.869062,797.265710,125.936240,14.293978,727.763429,191.367386,50.719442,294.839679
1,Afghanistan,AFG,1991,261.241824,41.376024,117.311719,823.233932,85.111020,989.709648,156.977412,...,28.275271,57.148890,174.183219,853.126362,133.781377,15.241048,766.040181,203.509622,54.317640,311.469065
2,Afghanistan,AFG,1992,284.443630,44.106315,128.071634,901.022100,92.240603,1078.459037,168.990462,...,30.718152,61.876100,188.382296,927.812846,144.287648,16.508833,820.956547,220.208033,59.144200,334.565964
3,Afghanistan,AFG,1993,313.136816,47.424854,141.429604,996.432762,101.206726,1192.064525,184.347737,...,33.835442,67.504857,205.250430,1017.964700,157.471005,18.038507,891.134162,240.718821,64.938582,362.486749
4,Afghanistan,AFG,1994,343.229715,50.710951,155.754606,1097.895223,110.679923,1316.505674,200.246949,...,37.103370,73.175879,222.383572,1110.997186,171.311262,19.606636,965.286072,262.324068,70.930355,390.334685
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5989,Zimbabwe,ZWE,2012,1218.763107,56.966136,162.131298,783.959361,115.203608,936.013607,420.658042,...,212.201798,95.507275,222.048414,729.985667,91.875318,129.861515,327.561748,56.997563,183.828475,454.914384
5990,Zimbabwe,ZWE,2013,1252.747896,58.735014,161.039807,790.077464,115.846418,928.096553,423.397684,...,213.262823,97.058488,229.271375,728.931891,92.187505,133.293669,332.080678,56.258170,187.740238,466.870431
5991,Zimbabwe,ZWE,2014,1308.483454,61.575167,161.512234,839.938132,121.251540,949.321368,434.314706,...,215.100202,99.866860,240.975514,733.693373,94.962460,139.024680,343.054396,56.235666,195.949471,487.183868
5992,Zimbabwe,ZWE,2015,1357.611713,63.757395,162.909299,862.707637,123.638675,956.138239,442.122976,...,218.011570,102.734862,250.586202,741.287816,96.335115,144.153296,349.937885,55.664075,202.577660,502.675582
5993,Zimbabwe,ZWE,2016,1411.242274,66.764985,164.929997,891.630167,126.800977,969.794783,453.711001,...,222.509943,106.303546,263.215193,752.224915,98.373710,150.350177,360.943556,55.460516,209.891064,523.521206

In [442]:
df.columns

Index(['Country', 'Code', 'Year', 'Liver cancer ', 'Kidney cancer ',
       'Larynx cancer ', 'Breast cancer ', 'Thyroid cancer ',
       'Stomach cancer ', 'Bladder cancer ', 'Uterine cancer ',
       'Ovarian cancer ', 'Cervical cancer ', 'Prostate cancer ',
       'Pancreatic cancer ', 'Esophageal cancer ', 'Testicular cancer ',
       'Nasopharynx cancer ', 'Other pharynx cancer ',
       'Colon and rectum cancer ', 'Non-melanoma skin cancer ',
       'Lip and oral cavity cancer ', 'Brain and nervous system cancer ',
       'Tracheal, bronchus, and lung cancer ',
       'Gallbladder and biliary tract cancer ', 'Malignant skin melanoma ',
       'Leukemia ', 'Hodgkin lymphoma ', 'Multiple myeloma ',
       'Other cancers '],
      dtype='object')

In [443]:
#checking for null values = 0, there is none, just code. 
df.isnull().any()

Country                                  False
Code                                      True
Year                                     False
Liver cancer                             False
Kidney cancer                            False
Larynx cancer                            False
Breast cancer                            False
Thyroid cancer                           False
Stomach cancer                           False
Bladder cancer                           False
Uterine cancer                           False
Ovarian cancer                           False
Cervical cancer                          False
Prostate cancer                          False
Pancreatic cancer                        False
Esophageal cancer                        False
Testicular cancer                        False
Nasopharynx cancer                       False
Other pharynx cancer                     False
Colon and rectum cancer                  False
Non-melanoma skin cancer                 False
Lip and oral cavity cancer               False
Brain and nervous system cancer          False
Tracheal, bronchus, and lung cancer      False
Gallbladder and biliary tract cancer     False
Malignant skin melanoma                  False
Leukemia                                 False
Hodgkin lymphoma                         False
Multiple myeloma                         False
Other cancers                            False
dtype: bool

In [444]:
# checking for non values "nan"
df.isna().any()

Country                                  False
Code                                      True
Year                                     False
Liver cancer                             False
Kidney cancer                            False
Larynx cancer                            False
Breast cancer                            False
Thyroid cancer                           False
Stomach cancer                           False
Bladder cancer                           False
Uterine cancer                           False
Ovarian cancer                           False
Cervical cancer                          False
Prostate cancer                          False
Pancreatic cancer                        False
Esophageal cancer                        False
Testicular cancer                        False
Nasopharynx cancer                       False
Other pharynx cancer                     False
Colon and rectum cancer                  False
Non-melanoma skin cancer                 False
Lip and oral cavity cancer               False
Brain and nervous system cancer          False
Tracheal, bronchus, and lung cancer      False
Gallbladder and biliary tract cancer     False
Malignant skin melanoma                  False
Leukemia                                 False
Hodgkin lymphoma                         False
Multiple myeloma                         False
Other cancers                            False
dtype: bool

In [445]:
#df["Country", value="Chile"]
df_chile = df[df['Country'] == 'Chile']
df_chile

,Country,Code,Year,Liver cancer,Kidney cancer,Larynx cancer,Breast cancer,Thyroid cancer,Stomach cancer,Bladder cancer,...,Non-melanoma skin cancer,Lip and oral cavity cancer,Brain and nervous system cancer,"Tracheal, bronchus, and lung cancer",Gallbladder and biliary tract cancer,Malignant skin melanoma,Leukemia,Hodgkin lymphoma,Multiple myeloma,Other cancers
1161,Chile,CHL,1990,532.876703,515.232673,133.827093,847.396590,73.041805,3134.143120,231.504649,...,32.626349,97.755759,213.076623,1791.384215,1969.260915,86.360362,548.067010,72.092037,164.228294,841.473676
1162,Chile,CHL,1991,538.671490,516.723079,127.096157,842.870478,71.927153,3037.340420,237.624048,...,33.321150,96.833770,212.220945,1772.532782,1914.879890,89.495491,544.225825,68.474469,171.298548,844.897982
1163,Chile,CHL,1992,550.046402,521.615500,125.099561,841.069976,71.678472,2985.138051,241.894555,...,34.711106,95.906394,211.407955,1753.372730,1884.973832,91.514175,540.045619,65.201519,178.315691,851.708711
1164,Chile,CHL,1993,573.266095,533.268435,127.160034,873.750546,73.735285,3033.882651,254.881965,...,37.313053,99.475111,216.366704,1805.859907,1921.499409,95.744256,550.937871,64.514955,188.692394,873.900124
1165,Chile,CHL,1994,599.583442,541.520721,131.898772,919.048631,76.151602,3133.928189,266.588986,...,40.928153,102.524076,223.341981,1877.857200,1970.327303,103.256296,562.251949,64.816380,201.915411,901.161325
1166,Chile,CHL,1995,629.832706,549.686609,137.807743,964.781056,78.760092,3255.131718,281.381457,...,46.369362,106.830714,230.644809,1978.311832,2023.750352,111.151865,574.446572,65.904636,217.654852,931.451437
1167,Chile,CHL,1996,653.748508,543.043405,134.010792,988.316988,79.669363,3293.899501,287.654178,...,54.353842,104.644455,236.004203,2020.047316,2040.855200,114.852926,584.140899,65.187711,234.110597,956.583463
1168,Chile,CHL,1997,681.261068,501.837536,132.498587,994.430098,78.871478,3323.835562,291.294429,...,75.197434,108.965771,235.971600,1999.872366,2042.707270,120.541122,587.298965,64.395632,251.178648,980.854894
1169,Chile,CHL,1998,697.114968,502.017821,129.933974,1030.017953,81.798451,3339.843451,300.588797,...,92.273469,111.719466,246.634272,2006.471897,2062.470993,126.197274,595.337043,59.051350,268.754355,987.529719
1170,Chile,CHL,1999,689.508117,493.266474,127.212286,1049.171344,85.192075,3400.745201,315.778881,...,104.925502,115.319322,252.621391,2036.972494,2082.714763,131.351419,610.089218,60.686500,285.107723,1001.735165
1171,Chile,CHL,2000,694.332425,493.237542,123.262410,1072.727907,87.619944,3409.301113,334.747082,...,117.056273,119.855062,264.642073,2066.964390,2100.366819,136.903535,621.611160,56.041700,299.877786,1030.450715
1172,Chile,CHL,2001,706.910144,501.680497,124.037231,1096.385514,89.440139,3436.119753,345.232125,...,127.504820,120.794586,278.366447,2137.500797,2110.304707,138.373850,642.357210,55.682814,311.649048,1052.435984
1173,Chile,CHL,2002,740.734806,514.331308,124.864042,1123.380780,93.130639,3497.592447,358.290859,...,138.299680,123.290722,287.440866,2207.981475,2146.288461,142.986631,656.678106,56.082787,327.124145,1066.441714
1174,Chile,CHL,2003,777.464309,528.214964,127.693700,1152.716822,96.087048,3546.167518,370.729141,...,148.193592,125.898086,298.060754,2278.296846,2166.970245,148.797983,671.295526,54.890272,342.018749,1088.290957
1175,Chile,CHL,2004,807.342306,553.481938,130.223832,1188.362166,96.457486,3578.684020,388.195901,...,158.600282,129.496351,314.402296,2378.629264,2165.926582,151.687885,680.951908,56.596715,355.415350,1122.362504
1176,Chile,CHL,2005,841.077847,577.238644,132.048868,1220.149235,97.805076,3579.942460,406.412628,...,170.098490,130.829509,323.290565,2446.769868,2169.956992,152.100728,691.260234,54.188966,363.887991,1138.249306
1177,Chile,CHL,2006,874.147854,586.734464,132.837489,1227.779486,99.652033,3562.311959,411.804897,...,175.832413,134.035891,333.797379,2510.729569,2144.089951,153.250314,698.403737,54.778761,370.400489,1154.075692
1178,Chile,CHL,2007,902.823384,602.781119,135.412662,1234.845267,102.395505,3541.004718,419.978624,...,187.370148,137.562075,351.182188,2568.930565,2123.729968,154.071901,708.823906,53.566151,377.236309,1165.327516
1179,Chile,CHL,2008,940.960525,623.652168,136.088919,1252.405624,102.789846,3553.188885,427.853489,...,198.295541,140.222577,369.481695,2627.912742,2104.063827,154.961488,719.317325,53.312858,385.516200,1178.864956
1180,Chile,CHL,2009,983.482151,652.472272,142.878291,1307.753629,108.527232,3680.861702,443.124426,...,216.545915,145.170994,388.406837,2755.643607,2148.921971,159.435475,734.730602,54.453156,400.634062,1215.700905
1181,Chile,CHL,2010,1027.755176,679.340779,146.718884,1355.631584,113.636203,3778.315993,465.419440,...,231.547995,151.826480,405.804648,2893.613938,2189.469179,169.818345,755.114700,57.452671,416.223181,1253.328540
1182,Chile,CHL,2011,1068.833695,703.535235,148.592511,1389.056614,114.328861,3789.974688,473.111820,...,236.917064,160.450809,419.295887,2977.303319,2213.560589,175.084686,773.878202,58.189945,431.315217,1286.793185
1183,Chile,CHL,2012,1118.124433,735.884294,151.581045,1425.894713,118.812314,3835.487320,483.744321,...,246.267866,169.105846,430.185290,3070.337311,2238.158281,175.643744,795.621367,58.800908,447.414123,1321.677971
1184,Chile,CHL,2013,1150.920440,759.334574,152.418107,1449.391506,122.586767,3858.277387,504.156666,...,251.633942,174.222781,442.209361,3180.096998,2246.496939,180.269010,815.230858,60.652703,462.135052,1348.687244
1185,Chile,CHL,2014,1190.102190,788.881915,155.403636,1461.112817,122.265797,3851.092663,529.283151,...,255.990275,175.360635,450.610437,3231.479369,2250.518045,189.904679,823.594805,62.114782,475.355126,1362.428474
1186,Chile,CHL,2015,1224.585997,811.959547,158.982017,1479.204915,124.450024,3934.473433,542.535154,...,261.085346,182.079642,457.575883,3317.311168,2323.259961,195.254873,833.094265,61.368792,491.660304,1404.888451
1187,Chile,CHL,2016,1265.944153,840.315118,163.967027,1510.971151,127.492652,4041.102792,562.622340,...,269.104746,188.435663,467.583356,3430.442325,2397.526696,202.422867,849.478485,61.812656,510.180060,1447.229304

In [446]:
# df["Country", value="Germany"]
df_germany = df[df['Country'] == 'Germany']
df_germany

,Country,Code,Year,Liver cancer,Kidney cancer,Larynx cancer,Breast cancer,Thyroid cancer,Stomach cancer,Bladder cancer,...,Non-melanoma skin cancer,Lip and oral cavity cancer,Brain and nervous system cancer,"Tracheal, bronchus, and lung cancer",Gallbladder and biliary tract cancer,Malignant skin melanoma,Leukemia,Hodgkin lymphoma,Multiple myeloma,Other cancers
2052,Germany,DEU,1990,3757.374920,5070.884825,1855.336341,18157.74796,887.084373,18064.03760,6554.166394,...,912.503814,2587.833099,4167.556276,39108.93070,6247.529503,1876.667209,7857.333928,685.792368,2462.848310,6590.828644
2053,Germany,DEU,1991,3806.755426,5175.336694,1863.910172,18357.45368,888.683344,17598.04676,6526.244891,...,903.641780,2679.627435,4283.779982,39474.99723,6025.398918,1864.884273,7849.369655,668.733752,2540.582270,6615.596593
2054,Germany,DEU,1992,4012.300112,5377.202082,1874.958860,18513.09420,876.688274,16985.78512,6457.869074,...,887.422104,2754.463253,4443.287477,39892.78800,5849.096515,1902.643714,7877.700042,628.122778,2589.777272,6594.899118
2055,Germany,DEU,1993,4226.851957,5477.157907,1866.609305,18717.06069,868.398282,16620.33808,6386.762284,...,877.020905,2782.202128,4596.437998,40290.14965,5751.288806,1921.823275,7972.960424,605.466193,2691.958905,6579.922129
2056,Germany,DEU,1994,4380.685176,5548.169025,1868.238055,18958.91876,856.514418,16087.02726,6353.730305,...,856.313978,2737.170454,4693.452519,40657.80024,5523.457457,1923.332672,8153.135545,572.599272,2774.171419,6581.043743
2057,Germany,DEU,1995,4691.199547,5595.011366,1856.012711,19128.57759,862.850826,15601.24402,6509.182054,...,831.267280,2729.196041,4805.089800,41254.50524,5143.782954,1951.046760,8280.475759,567.470814,2939.733231,6945.056141
2058,Germany,DEU,1996,4879.421622,5648.899141,1816.366622,19218.90113,847.429306,15460.33030,6564.281433,...,812.728501,2705.160448,4923.434772,41589.46341,4986.808827,1994.038583,8417.152388,556.825092,3072.148396,7058.623038
2059,Germany,DEU,1997,5018.973185,5682.366484,1789.692987,19024.63541,846.090500,15026.89728,6536.192025,...,795.974530,2642.001978,5007.893275,41654.17138,4811.371950,2053.122612,8557.000130,543.938860,3186.577955,6954.382194
2060,Germany,DEU,1998,5267.195405,5811.309260,1728.804693,18760.82886,849.329473,15070.75928,6412.480983,...,806.193078,2549.859427,5207.192765,41516.10513,4941.767243,2104.080636,8772.796088,526.093612,3279.206331,6875.859234
2061,Germany,DEU,1999,5434.287871,5823.306824,1706.500441,18616.54558,836.691553,14855.11490,6347.416730,...,808.256294,2503.345760,5299.967549,41565.43048,4933.399296,2162.391232,8898.030766,514.775364,3333.464606,6832.940924
2062,Germany,DEU,2000,5613.300987,5804.962474,1697.300860,18567.36217,822.298765,14593.68961,6275.411085,...,828.971773,2469.539972,5362.451900,41670.89222,4880.038554,2237.053333,9028.552248,491.249548,3379.056587,6945.236395
2063,Germany,DEU,2001,5775.909087,5805.131262,1665.418024,18504.57284,806.746567,14339.15452,6187.150777,...,840.895392,2468.486016,5407.884365,41521.37757,4867.138666,2284.583300,9134.616885,472.232784,3423.486417,7004.601705
2064,Germany,DEU,2002,5937.658440,5782.042802,1660.585546,18540.57877,792.760566,14165.21947,6140.133570,...,863.958339,2444.201771,5444.585004,41730.19479,4804.267173,2339.472044,9192.687779,454.425262,3463.212396,7073.337575
2065,Germany,DEU,2003,6143.642993,5794.616150,1649.540281,18481.97343,785.461158,13904.96934,6123.077422,...,885.487970,2433.444248,5486.119054,42010.66206,4721.393790,2391.858641,9275.995970,445.919607,3493.167020,7184.711751
2066,Germany,DEU,2004,6315.312612,5835.101040,1635.487807,18450.48851,772.985593,13665.19251,6113.376655,...,908.485649,2429.589577,5512.557122,42267.21230,4649.716605,2441.480778,9373.034549,437.339770,3536.852807,7356.994199
2067,Germany,DEU,2005,6510.191194,5921.127156,1633.842279,18589.27975,780.601524,13550.53091,6156.065933,...,940.939320,2446.281082,5558.457172,42819.60270,4597.211110,2507.194058,9528.193109,434.211503,3587.383411,7574.252119
2068,Germany,DEU,2006,6761.754437,6008.305967,1625.008395,18644.46060,785.049375,13351.72737,6217.232353,...,966.285168,2463.327371,5589.143616,43246.56972,4548.525241,2570.609539,9633.441857,425.782796,3633.628426,7823.178528
2069,Germany,DEU,2007,6947.605147,6098.190158,1608.830113,18666.74097,785.791773,13222.79102,6287.946774,...,977.507658,2493.363071,5616.755366,43718.32711,4483.108422,2649.455390,9711.872139,417.627766,3686.370191,8067.833718
2070,Germany,DEU,2008,7147.028027,6223.018750,1604.484733,18837.98433,797.529142,13072.45811,6366.677719,...,999.318593,2524.757426,5663.479305,44289.93276,4443.360720,2741.661768,9799.766193,417.231334,3740.517911,8363.656059
2071,Germany,DEU,2009,7336.253199,6343.508902,1594.223561,18923.71162,808.189639,13026.61898,6451.633093,...,1022.419391,2551.823008,5727.193372,44925.51113,4425.269112,2826.644601,9876.609410,415.327887,3799.704242,8675.644071
2072,Germany,DEU,2010,7511.043379,6467.132063,1586.879650,18911.36382,818.234783,12983.57170,6587.807020,...,1042.270109,2588.056002,5772.186415,45468.41595,4424.296249,2896.909226,9915.087488,413.112449,3869.218443,9024.497896
2073,Germany,DEU,2011,7645.233730,6592.646946,1577.292312,18849.00083,832.176477,12959.01716,6769.713575,...,1049.743470,2621.112661,5812.756802,45703.50642,4446.585891,2956.497028,9875.894371,411.106992,3930.879845,9463.950363
2074,Germany,DEU,2012,7758.972017,6711.154048,1564.680238,18797.26131,847.964754,12985.60945,6906.156492,...,1065.652704,2653.951008,5864.108260,46063.62581,4473.403385,3008.956142,9890.949119,411.760173,3987.339428,9808.224214
2075,Germany,DEU,2013,7846.717381,6836.387425,1564.721915,18774.86517,862.289837,12972.87044,7043.675081,...,1085.115111,2684.013225,5916.709077,46444.81032,4511.130553,3067.438682,9949.222558,409.360496,4054.026060,10086.648710
2076,Germany,DEU,2014,7946.802085,6926.774727,1550.987239,18619.41778,863.366821,12871.27631,7149.755530,...,1098.054684,2702.548414,5983.262107,46407.73067,4527.216307,3102.645760,9962.849274,404.279128,4103.547804,10269.343220
2077,Germany,DEU,2015,8040.209986,7062.175645,1549.620648,18615.36917,869.293248,13057.06670,7337.289187,...,1119.642110,2728.535250,6032.296143,46595.96113,4579.884648,3124.854494,10125.876920,403.995263,4180.160856,10252.073800
2078,Germany,DEU,2016,8164.172707,7206.504844,1556.921490,18726.27221,878.868040,13254.25400,7531.119672,...,1146.445598,2762.572216,6103.834210,47003.50954,4647.629808,3165.783065,10288.294220,404.405435,4266.358908,10344.008880

In [447]:
# checking for duplicates
df.duplicated().any()

False

In [448]:
# Are Chile and Germany in the list of countries?
df["Country"].unique()

array(['Afghanistan', 'Albania', 'Algeria', 'American Samoa',
       'Andean Latin America', 'Andorra', 'Angola', 'Antigua and Barbuda',
       'Argentina', 'Armenia', 'Australasia', 'Australia', 'Austria',
       'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados',
       'Belarus', 'Belgium', 'Belize', 'Benin', 'Bermuda', 'Bhutan',
       'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil',
       'Brunei', 'Bulgaria', 'Burkina Faso', 'Burundi', 'Cambodia',
       'Cameroon', 'Canada', 'Cape Verde', 'Caribbean',
       'Central African Republic', 'Central Asia', 'Central Europe',
       'Central Latin America', 'Central Sub-Saharan Africa', 'Chad',
       'Chile', 'China', 'Colombia', 'Comoros', 'Congo', 'Costa Rica',
       "Cote d'Ivoire", 'Croatia', 'Cuba', 'Cyprus', 'Czech Republic',
       'Democratic Republic of Congo', 'Denmark', 'Djibouti', 'Dominica',
       'Dominican Republic', 'East Asia', 'Eastern Europe',
       'Eastern Sub-Saharan Africa', 'Ecuador', 'Egypt', 'El Salvador',
       'England', 'Equatorial Guinea', 'Eritrea', 'Estonia', 'Ethiopia',
       'Fiji', 'Finland', 'France', 'Gabon', 'Gambia', 'Georgia',
       'Germany', 'Ghana', 'Greece', 'Greenland', 'Grenada', 'Guam',
       'Guatemala', 'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti',
       'Honduras', 'Hungary', 'Iceland', 'India', 'Indonesia', 'Iran',
       'Iraq', 'Ireland', 'Israel', 'Italy', 'Jamaica', 'Japan', 'Jordan',
       'Kazakhstan', 'Kenya', 'Kiribati', 'Kuwait', 'Kyrgyzstan', 'Laos',
       'Latin America and Caribbean', 'Latvia', 'Lebanon', 'Lesotho',
       'Liberia', 'Libya', 'Lithuania', 'Luxembourg', 'Macedonia',
       'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta',
       'Marshall Islands', 'Mauritania', 'Mauritius', 'Mexico',
       'Micronesia (country)', 'Moldova', 'Mongolia', 'Montenegro',
       'Morocco', 'Mozambique', 'Myanmar', 'Namibia', 'Nepal',
       'Netherlands', 'New Zealand', 'Nicaragua', 'Niger', 'Nigeria',
       'North Africa and Middle East', 'North America', 'North Korea',
       'Northern Ireland', 'Northern Mariana Islands', 'Norway',
       'Oceania', 'Oman', 'Pakistan', 'Palestine', 'Panama',
       'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Poland',
       'Portugal', 'Puerto Rico', 'Qatar', 'Romania', 'Russia', 'Rwanda',
       'Saint Lucia', 'Saint Vincent and the Grenadines', 'Samoa',
       'Sao Tome and Principe', 'Saudi Arabia', 'Scotland', 'Senegal',
       'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore', 'Slovakia',
       'Slovenia', 'Solomon Islands', 'Somalia', 'South Africa',
       'South Asia', 'South Korea', 'South Sudan', 'Southeast Asia',
       'Southern Latin America', 'Southern Sub-Saharan Africa', 'Spain',
       'Sri Lanka', 'Sub-Saharan Africa', 'Sudan', 'Suriname',
       'Swaziland', 'Sweden', 'Switzerland', 'Syria', 'Taiwan',
       'Tajikistan', 'Tanzania', 'Thailand', 'Timor', 'Togo', 'Tonga',
       'Trinidad and Tobago', 'Tropical Latin America', 'Tunisia',
       'Turkey', 'Turkmenistan', 'Uganda', 'Ukraine',
       'United Arab Emirates', 'United Kingdom', 'United States',
       'United States Virgin Islands', 'Uruguay', 'Uzbekistan', 'Vanuatu',
       'Venezuela', 'Vietnam', 'Wales', 'Western Europe',
       'Western Sub-Saharan Africa', 'World', 'Yemen', 'Zambia',
       'Zimbabwe'], dtype=object)

In [449]:
from bs4 import BeautifulSoup
import requests

In [450]:
url2 = "https://www.worldometers.info/world-population/chile-population/"
url3 = "https://www.worldometers.info/world-population/germany-population/"

In [451]:
response2 = requests.get(url2)
response2

In [452]:
response3 = requests.get(url3)
response3

In [453]:
soup2 = BeautifulSoup(response2.content,"html.parser") # putting them into parts

In [454]:
#soup2

In [455]:
soup3 = BeautifulSoup(response3.content,"html.parser")

In [456]:
#soup3

In [457]:
#print(soup3.prettify())

In [458]:
#print(soup2.prettify())

In [542]:
# df["Country", value="Chile"]
df_chile = df[df['Country'] == 'Chile']
df_chile

,Country,Code,Year,Liver cancer,Kidney cancer,Larynx cancer,Breast cancer,Thyroid cancer,Stomach cancer,Bladder cancer,...,Non-melanoma skin cancer,Lip and oral cavity cancer,Brain and nervous system cancer,"Tracheal, bronchus, and lung cancer",Gallbladder and biliary tract cancer,Malignant skin melanoma,Leukemia,Hodgkin lymphoma,Multiple myeloma,Other cancers
1161,Chile,CHL,1990,532.876703,515.232673,133.827093,847.396590,73.041805,3134.143120,231.504649,...,32.626349,97.755759,213.076623,1791.384215,1969.260915,86.360362,548.067010,72.092037,164.228294,841.473676
1162,Chile,CHL,1991,538.671490,516.723079,127.096157,842.870478,71.927153,3037.340420,237.624048,...,33.321150,96.833770,212.220945,1772.532782,1914.879890,89.495491,544.225825,68.474469,171.298548,844.897982
1163,Chile,CHL,1992,550.046402,521.615500,125.099561,841.069976,71.678472,2985.138051,241.894555,...,34.711106,95.906394,211.407955,1753.372730,1884.973832,91.514175,540.045619,65.201519,178.315691,851.708711
1164,Chile,CHL,1993,573.266095,533.268435,127.160034,873.750546,73.735285,3033.882651,254.881965,...,37.313053,99.475111,216.366704,1805.859907,1921.499409,95.744256,550.937871,64.514955,188.692394,873.900124
1165,Chile,CHL,1994,599.583442,541.520721,131.898772,919.048631,76.151602,3133.928189,266.588986,...,40.928153,102.524076,223.341981,1877.857200,1970.327303,103.256296,562.251949,64.816380,201.915411,901.161325
1166,Chile,CHL,1995,629.832706,549.686609,137.807743,964.781056,78.760092,3255.131718,281.381457,...,46.369362,106.830714,230.644809,1978.311832,2023.750352,111.151865,574.446572,65.904636,217.654852,931.451437
1167,Chile,CHL,1996,653.748508,543.043405,134.010792,988.316988,79.669363,3293.899501,287.654178,...,54.353842,104.644455,236.004203,2020.047316,2040.855200,114.852926,584.140899,65.187711,234.110597,956.583463
1168,Chile,CHL,1997,681.261068,501.837536,132.498587,994.430098,78.871478,3323.835562,291.294429,...,75.197434,108.965771,235.971600,1999.872366,2042.707270,120.541122,587.298965,64.395632,251.178648,980.854894
1169,Chile,CHL,1998,697.114968,502.017821,129.933974,1030.017953,81.798451,3339.843451,300.588797,...,92.273469,111.719466,246.634272,2006.471897,2062.470993,126.197274,595.337043,59.051350,268.754355,987.529719
1170,Chile,CHL,1999,689.508117,493.266474,127.212286,1049.171344,85.192075,3400.745201,315.778881,...,104.925502,115.319322,252.621391,2036.972494,2082.714763,131.351419,610.089218,60.686500,285.107723,1001.735165
1171,Chile,CHL,2000,694.332425,493.237542,123.262410,1072.727907,87.619944,3409.301113,334.747082,...,117.056273,119.855062,264.642073,2066.964390,2100.366819,136.903535,621.611160,56.041700,299.877786,1030.450715
1172,Chile,CHL,2001,706.910144,501.680497,124.037231,1096.385514,89.440139,3436.119753,345.232125,...,127.504820,120.794586,278.366447,2137.500797,2110.304707,138.373850,642.357210,55.682814,311.649048,1052.435984
1173,Chile,CHL,2002,740.734806,514.331308,124.864042,1123.380780,93.130639,3497.592447,358.290859,...,138.299680,123.290722,287.440866,2207.981475,2146.288461,142.986631,656.678106,56.082787,327.124145,1066.441714
1174,Chile,CHL,2003,777.464309,528.214964,127.693700,1152.716822,96.087048,3546.167518,370.729141,...,148.193592,125.898086,298.060754,2278.296846,2166.970245,148.797983,671.295526,54.890272,342.018749,1088.290957
1175,Chile,CHL,2004,807.342306,553.481938,130.223832,1188.362166,96.457486,3578.684020,388.195901,...,158.600282,129.496351,314.402296,2378.629264,2165.926582,151.687885,680.951908,56.596715,355.415350,1122.362504
1176,Chile,CHL,2005,841.077847,577.238644,132.048868,1220.149235,97.805076,3579.942460,406.412628,...,170.098490,130.829509,323.290565,2446.769868,2169.956992,152.100728,691.260234,54.188966,363.887991,1138.249306
1177,Chile,CHL,2006,874.147854,586.734464,132.837489,1227.779486,99.652033,3562.311959,411.804897,...,175.832413,134.035891,333.797379,2510.729569,2144.089951,153.250314,698.403737,54.778761,370.400489,1154.075692
1178,Chile,CHL,2007,902.823384,602.781119,135.412662,1234.845267,102.395505,3541.004718,419.978624,...,187.370148,137.562075,351.182188,2568.930565,2123.729968,154.071901,708.823906,53.566151,377.236309,1165.327516
1179,Chile,CHL,2008,940.960525,623.652168,136.088919,1252.405624,102.789846,3553.188885,427.853489,...,198.295541,140.222577,369.481695,2627.912742,2104.063827,154.961488,719.317325,53.312858,385.516200,1178.864956
1180,Chile,CHL,2009,983.482151,652.472272,142.878291,1307.753629,108.527232,3680.861702,443.124426,...,216.545915,145.170994,388.406837,2755.643607,2148.921971,159.435475,734.730602,54.453156,400.634062,1215.700905
1181,Chile,CHL,2010,1027.755176,679.340779,146.718884,1355.631584,113.636203,3778.315993,465.419440,...,231.547995,151.826480,405.804648,2893.613938,2189.469179,169.818345,755.114700,57.452671,416.223181,1253.328540
1182,Chile,CHL,2011,1068.833695,703.535235,148.592511,1389.056614,114.328861,3789.974688,473.111820,...,236.917064,160.450809,419.295887,2977.303319,2213.560589,175.084686,773.878202,58.189945,431.315217,1286.793185
1183,Chile,CHL,2012,1118.124433,735.884294,151.581045,1425.894713,118.812314,3835.487320,483.744321,...,246.267866,169.105846,430.185290,3070.337311,2238.158281,175.643744,795.621367,58.800908,447.414123,1321.677971
1184,Chile,CHL,2013,1150.920440,759.334574,152.418107,1449.391506,122.586767,3858.277387,504.156666,...,251.633942,174.222781,442.209361,3180.096998,2246.496939,180.269010,815.230858,60.652703,462.135052,1348.687244
1185,Chile,CHL,2014,1190.102190,788.881915,155.403636,1461.112817,122.265797,3851.092663,529.283151,...,255.990275,175.360635,450.610437,3231.479369,2250.518045,189.904679,823.594805,62.114782,475.355126,1362.428474
1186,Chile,CHL,2015,1224.585997,811.959547,158.982017,1479.204915,124.450024,3934.473433,542.535154,...,261.085346,182.079642,457.575883,3317.311168,2323.259961,195.254873,833.094265,61.368792,491.660304,1404.888451
1187,Chile,CHL,2016,1265.944153,840.315118,163.967027,1510.971151,127.492652,4041.102792,562.622340,...,269.104746,188.435663,467.583356,3430.442325,2397.526696,202.422867,849.478485,61.812656,510.180060,1447.229304

In [544]:
# how to set the index to 0?
# df_chile.set_index(inplace=True)

In [461]:
# df["Country", value="Germany"]
df_germany = df[df['Country'] == 'Germany']
df_germany

,Country,Code,Year,Liver cancer,Kidney cancer,Larynx cancer,Breast cancer,Thyroid cancer,Stomach cancer,Bladder cancer,...,Non-melanoma skin cancer,Lip and oral cavity cancer,Brain and nervous system cancer,"Tracheal, bronchus, and lung cancer",Gallbladder and biliary tract cancer,Malignant skin melanoma,Leukemia,Hodgkin lymphoma,Multiple myeloma,Other cancers
2052,Germany,DEU,1990,3757.374920,5070.884825,1855.336341,18157.74796,887.084373,18064.03760,6554.166394,...,912.503814,2587.833099,4167.556276,39108.93070,6247.529503,1876.667209,7857.333928,685.792368,2462.848310,6590.828644
2053,Germany,DEU,1991,3806.755426,5175.336694,1863.910172,18357.45368,888.683344,17598.04676,6526.244891,...,903.641780,2679.627435,4283.779982,39474.99723,6025.398918,1864.884273,7849.369655,668.733752,2540.582270,6615.596593
2054,Germany,DEU,1992,4012.300112,5377.202082,1874.958860,18513.09420,876.688274,16985.78512,6457.869074,...,887.422104,2754.463253,4443.287477,39892.78800,5849.096515,1902.643714,7877.700042,628.122778,2589.777272,6594.899118
2055,Germany,DEU,1993,4226.851957,5477.157907,1866.609305,18717.06069,868.398282,16620.33808,6386.762284,...,877.020905,2782.202128,4596.437998,40290.14965,5751.288806,1921.823275,7972.960424,605.466193,2691.958905,6579.922129
2056,Germany,DEU,1994,4380.685176,5548.169025,1868.238055,18958.91876,856.514418,16087.02726,6353.730305,...,856.313978,2737.170454,4693.452519,40657.80024,5523.457457,1923.332672,8153.135545,572.599272,2774.171419,6581.043743
2057,Germany,DEU,1995,4691.199547,5595.011366,1856.012711,19128.57759,862.850826,15601.24402,6509.182054,...,831.267280,2729.196041,4805.089800,41254.50524,5143.782954,1951.046760,8280.475759,567.470814,2939.733231,6945.056141
2058,Germany,DEU,1996,4879.421622,5648.899141,1816.366622,19218.90113,847.429306,15460.33030,6564.281433,...,812.728501,2705.160448,4923.434772,41589.46341,4986.808827,1994.038583,8417.152388,556.825092,3072.148396,7058.623038
2059,Germany,DEU,1997,5018.973185,5682.366484,1789.692987,19024.63541,846.090500,15026.89728,6536.192025,...,795.974530,2642.001978,5007.893275,41654.17138,4811.371950,2053.122612,8557.000130,543.938860,3186.577955,6954.382194
2060,Germany,DEU,1998,5267.195405,5811.309260,1728.804693,18760.82886,849.329473,15070.75928,6412.480983,...,806.193078,2549.859427,5207.192765,41516.10513,4941.767243,2104.080636,8772.796088,526.093612,3279.206331,6875.859234
2061,Germany,DEU,1999,5434.287871,5823.306824,1706.500441,18616.54558,836.691553,14855.11490,6347.416730,...,808.256294,2503.345760,5299.967549,41565.43048,4933.399296,2162.391232,8898.030766,514.775364,3333.464606,6832.940924
2062,Germany,DEU,2000,5613.300987,5804.962474,1697.300860,18567.36217,822.298765,14593.68961,6275.411085,...,828.971773,2469.539972,5362.451900,41670.89222,4880.038554,2237.053333,9028.552248,491.249548,3379.056587,6945.236395
2063,Germany,DEU,2001,5775.909087,5805.131262,1665.418024,18504.57284,806.746567,14339.15452,6187.150777,...,840.895392,2468.486016,5407.884365,41521.37757,4867.138666,2284.583300,9134.616885,472.232784,3423.486417,7004.601705
2064,Germany,DEU,2002,5937.658440,5782.042802,1660.585546,18540.57877,792.760566,14165.21947,6140.133570,...,863.958339,2444.201771,5444.585004,41730.19479,4804.267173,2339.472044,9192.687779,454.425262,3463.212396,7073.337575
2065,Germany,DEU,2003,6143.642993,5794.616150,1649.540281,18481.97343,785.461158,13904.96934,6123.077422,...,885.487970,2433.444248,5486.119054,42010.66206,4721.393790,2391.858641,9275.995970,445.919607,3493.167020,7184.711751
2066,Germany,DEU,2004,6315.312612,5835.101040,1635.487807,18450.48851,772.985593,13665.19251,6113.376655,...,908.485649,2429.589577,5512.557122,42267.21230,4649.716605,2441.480778,9373.034549,437.339770,3536.852807,7356.994199
2067,Germany,DEU,2005,6510.191194,5921.127156,1633.842279,18589.27975,780.601524,13550.53091,6156.065933,...,940.939320,2446.281082,5558.457172,42819.60270,4597.211110,2507.194058,9528.193109,434.211503,3587.383411,7574.252119
2068,Germany,DEU,2006,6761.754437,6008.305967,1625.008395,18644.46060,785.049375,13351.72737,6217.232353,...,966.285168,2463.327371,5589.143616,43246.56972,4548.525241,2570.609539,9633.441857,425.782796,3633.628426,7823.178528
2069,Germany,DEU,2007,6947.605147,6098.190158,1608.830113,18666.74097,785.791773,13222.79102,6287.946774,...,977.507658,2493.363071,5616.755366,43718.32711,4483.108422,2649.455390,9711.872139,417.627766,3686.370191,8067.833718
2070,Germany,DEU,2008,7147.028027,6223.018750,1604.484733,18837.98433,797.529142,13072.45811,6366.677719,...,999.318593,2524.757426,5663.479305,44289.93276,4443.360720,2741.661768,9799.766193,417.231334,3740.517911,8363.656059
2071,Germany,DEU,2009,7336.253199,6343.508902,1594.223561,18923.71162,808.189639,13026.61898,6451.633093,...,1022.419391,2551.823008,5727.193372,44925.51113,4425.269112,2826.644601,9876.609410,415.327887,3799.704242,8675.644071
2072,Germany,DEU,2010,7511.043379,6467.132063,1586.879650,18911.36382,818.234783,12983.57170,6587.807020,...,1042.270109,2588.056002,5772.186415,45468.41595,4424.296249,2896.909226,9915.087488,413.112449,3869.218443,9024.497896
2073,Germany,DEU,2011,7645.233730,6592.646946,1577.292312,18849.00083,832.176477,12959.01716,6769.713575,...,1049.743470,2621.112661,5812.756802,45703.50642,4446.585891,2956.497028,9875.894371,411.106992,3930.879845,9463.950363
2074,Germany,DEU,2012,7758.972017,6711.154048,1564.680238,18797.26131,847.964754,12985.60945,6906.156492,...,1065.652704,2653.951008,5864.108260,46063.62581,4473.403385,3008.956142,9890.949119,411.760173,3987.339428,9808.224214
2075,Germany,DEU,2013,7846.717381,6836.387425,1564.721915,18774.86517,862.289837,12972.87044,7043.675081,...,1085.115111,2684.013225,5916.709077,46444.81032,4511.130553,3067.438682,9949.222558,409.360496,4054.026060,10086.648710
2076,Germany,DEU,2014,7946.802085,6926.774727,1550.987239,18619.41778,863.366821,12871.27631,7149.755530,...,1098.054684,2702.548414,5983.262107,46407.73067,4527.216307,3102.645760,9962.849274,404.279128,4103.547804,10269.343220
2077,Germany,DEU,2015,8040.209986,7062.175645,1549.620648,18615.36917,869.293248,13057.06670,7337.289187,...,1119.642110,2728.535250,6032.296143,46595.96113,4579.884648,3124.854494,10125.876920,403.995263,4180.160856,10252.073800
2078,Germany,DEU,2016,8164.172707,7206.504844,1556.921490,18726.27221,878.868040,13254.25400,7531.119672,...,1146.445598,2762.572216,6103.834210,47003.50954,4647.629808,3165.783065,10288.294220,404.405435,4266.358908,10344.008880

In [462]:
# Locate the table with population counts over the years
table2 = soup2.find('table', {'class': 'table table-striped table-bordered table-hover table-condensed table-list'})
#table2 (to check if it works)

In [463]:
# Extract population data from the table
population_data_chile = []
for row in table2.find('tbody').find_all('tr'):
    cells = row.find_all('td')
    if len(cells) > 1:  # Ensure it's a valid row with data
        year = cells[0].text.strip()  # Year column
        population = cells[1].text.strip()  # Population column
        population_data_chile.append((year, population))
# Print the extracted data
for year, population in population_data_chile: #### created population data chile
    print(f"Year: {year}, Population: {population}")

Year: 2025, Population: 19,859,921
Year: 2024, Population: 19,764,771
Year: 2023, Population: 19,658,835
Year: 2022, Population: 19,553,036
Year: 2020, Population: 19,370,624
Year: 2015, Population: 18,047,625
Year: 2010, Population: 17,181,464
Year: 2005, Population: 16,348,778
Year: 2000, Population: 15,503,635
Year: 1995, Population: 14,527,381
Year: 1990, Population: 13,437,176
Year: 1985, Population: 12,395,274
Year: 1980, Population: 11,508,550
Year: 1975, Population: 10,671,559
Year: 1970, Population: 9,845,344
Year: 1965, Population: 9,012,938
Year: 1960, Population: 8,153,350
Year: 1955, Population: 7,332,301

In [464]:
#population_data_chile

In [465]:
# Locate the table with population counts over the years
table3 = soup3.find('table', {'class': 'table table-striped table-bordered table-hover table-condensed table-list'})
#table3 (to check if it works)

In [466]:
# Extract population data from the table
population_data_germany = []
for row in table3.find('tbody').find_all('tr'):
    cells = row.find_all('td')
    if len(cells) > 1:  # Ensure it's a valid row with data
        year = cells[0].text.strip()  # Year column
        population = cells[1].text.strip()  # Population column
        population_data_germany.append((year, population))
# Print the extracted data
for year, population in population_data_germany:# created population data germany 
    print(f"Year: {year}, Population: {population}")

Year: 2025, Population: 84,075,075
Year: 2024, Population: 84,552,242
Year: 2023, Population: 84,548,231
Year: 2022, Population: 84,086,227
Year: 2020, Population: 83,628,708
Year: 2015, Population: 82,077,550
Year: 2010, Population: 80,830,924
Year: 2005, Population: 82,046,731
Year: 2000, Population: 81,797,258
Year: 1995, Population: 82,019,890
Year: 1990, Population: 79,707,959
Year: 1985, Population: 77,863,424
Year: 1980, Population: 78,315,375
Year: 1975, Population: 78,701,865
Year: 1970, Population: 78,205,102
Year: 1965, Population: 75,966,964
Year: 1960, Population: 72,811,640
Year: 1955, Population: 70,334,152

In [467]:
#population_data_germany

In [468]:
# Adding a "Country" column to the Population Count Lists:

# for row in population_data_germany:
#    row["Country"] = "Germany"
# population_data_germany

# Does not work, because Population Count Lists are Tuple pairs in a list

In [469]:
# We don´t need to add the Country to the Population lists, because we have separat Cancer Death DFs for Germany and Chile
# Create DFs from Population Data
df_germany_population = pd.DataFrame(population_data_germany)
df_germany_population

       0           1
0   2025  84,075,075
1   2024  84,552,242
2   2023  84,548,231
3   2022  84,086,227
4   2020  83,628,708
5   2015  82,077,550
6   2010  80,830,924
7   2005  82,046,731
8   2000  81,797,258
9   1995  82,019,890
10  1990  79,707,959
11  1985  77,863,424
12  1980  78,315,375
13  1975  78,701,865
14  1970  78,205,102
15  1965  75,966,964
16  1960  72,811,640
17  1955  70,334,152

In [470]:
# Naming the Columns with "Year" and "Population"
df_germany_population.rename(columns={0: "Year"}, inplace=True)
df_germany_population.rename(columns={1: "Population"}, inplace=True)
df_germany_population

    Year  Population
0   2025  84,075,075
1   2024  84,552,242
2   2023  84,548,231
3   2022  84,086,227
4   2020  83,628,708
5   2015  82,077,550
6   2010  80,830,924
7   2005  82,046,731
8   2000  81,797,258
9   1995  82,019,890
10  1990  79,707,959
11  1985  77,863,424
12  1980  78,315,375
13  1975  78,701,865
14  1970  78,205,102
15  1965  75,966,964
16  1960  72,811,640
17  1955  70,334,152

In [471]:
df_germany_population.dtypes

Year          object
Population    object
dtype: object

In [472]:
# Change Population DF data types into integers
df_germany_population["Year"] = df_germany_population["Year"].astype(int)
# The Population Count is a string containing comma, which need to be deleted first!
df_germany_population["Population"] = df_germany_population["Population"].str.replace(",", "").astype(int)
df_germany_population.dtypes

Year          int32
Population    int32
dtype: object

In [473]:
df_germany.dtypes

Country                                   object
Code                                      object
Year                                       int64
Liver cancer                             float64
Kidney cancer                            float64
Larynx cancer                            float64
Breast cancer                            float64
Thyroid cancer                           float64
Stomach cancer                           float64
Bladder cancer                           float64
Uterine cancer                           float64
Ovarian cancer                           float64
Cervical cancer                          float64
Prostate cancer                          float64
Pancreatic cancer                        float64
Esophageal cancer                        float64
Testicular cancer                        float64
Nasopharynx cancer                       float64
Other pharynx cancer                     float64
Colon and rectum cancer                  float64
Non-melanoma skin cancer                 float64
Lip and oral cavity cancer               float64
Brain and nervous system cancer          float64
Tracheal, bronchus, and lung cancer      float64
Gallbladder and biliary tract cancer     float64
Malignant skin melanoma                  float64
Leukemia                                 float64
Hodgkin lymphoma                         float64
Multiple myeloma                         float64
Other cancers                            float64
dtype: object

In [474]:
# Change Year format of Cancer Death tables into integer
df_germany["Year"] = df_germany["Year"].astype(int)
df_germany.dtypes

C:\Users\admin\AppData\Local\Temp\ipykernel_42272\734378569.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_germany["Year"] = df_germany["Year"].astype(int)

Country                                   object
Code                                      object
Year                                       int32
Liver cancer                             float64
Kidney cancer                            float64
Larynx cancer                            float64
Breast cancer                            float64
Thyroid cancer                           float64
Stomach cancer                           float64
Bladder cancer                           float64
Uterine cancer                           float64
Ovarian cancer                           float64
Cervical cancer                          float64
Prostate cancer                          float64
Pancreatic cancer                        float64
Esophageal cancer                        float64
Testicular cancer                        float64
Nasopharynx cancer                       float64
Other pharynx cancer                     float64
Colon and rectum cancer                  float64
Non-melanoma skin cancer                 float64
Lip and oral cavity cancer               float64
Brain and nervous system cancer          float64
Tracheal, bronchus, and lung cancer      float64
Gallbladder and biliary tract cancer     float64
Malignant skin melanoma                  float64
Leukemia                                 float64
Hodgkin lymphoma                         float64
Multiple myeloma                         float64
Other cancers                            float64
dtype: object

In [475]:
# Concatenating Population tables with Cancer Death tables
df_germany_cancer_population = pd.merge(df_germany, df_germany_population, on='Year', how="outer")
df_germany_cancer_population

,Country,Code,Year,Liver cancer,Kidney cancer,Larynx cancer,Breast cancer,Thyroid cancer,Stomach cancer,Bladder cancer,...,Lip and oral cavity cancer,Brain and nervous system cancer,"Tracheal, bronchus, and lung cancer",Gallbladder and biliary tract cancer,Malignant skin melanoma,Leukemia,Hodgkin lymphoma,Multiple myeloma,Other cancers,Population
0,NaN,NaN,1955,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,70334152.0
1,NaN,NaN,1960,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,72811640.0
2,NaN,NaN,1965,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,75966964.0
3,NaN,NaN,1970,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,78205102.0
4,NaN,NaN,1975,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,78701865.0
5,NaN,NaN,1980,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,78315375.0
6,NaN,NaN,1985,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,77863424.0
7,Germany,DEU,1990,3757.374920,5070.884825,1855.336341,18157.74796,887.084373,18064.03760,6554.166394,...,2587.833099,4167.556276,39108.93070,6247.529503,1876.667209,7857.333928,685.792368,2462.848310,6590.828644,79707959.0
8,Germany,DEU,1991,3806.755426,5175.336694,1863.910172,18357.45368,888.683344,17598.04676,6526.244891,...,2679.627435,4283.779982,39474.99723,6025.398918,1864.884273,7849.369655,668.733752,2540.582270,6615.596593,NaN
9,Germany,DEU,1992,4012.300112,5377.202082,1874.958860,18513.09420,876.688274,16985.78512,6457.869074,...,2754.463253,4443.287477,39892.78800,5849.096515,1902.643714,7877.700042,628.122778,2589.777272,6594.899118,NaN
10,Germany,DEU,1993,4226.851957,5477.157907,1866.609305,18717.06069,868.398282,16620.33808,6386.762284,...,2782.202128,4596.437998,40290.14965,5751.288806,1921.823275,7972.960424,605.466193,2691.958905,6579.922129,NaN
11,Germany,DEU,1994,4380.685176,5548.169025,1868.238055,18958.91876,856.514418,16087.02726,6353.730305,...,2737.170454,4693.452519,40657.80024,5523.457457,1923.332672,8153.135545,572.599272,2774.171419,6581.043743,NaN
12,Germany,DEU,1995,4691.199547,5595.011366,1856.012711,19128.57759,862.850826,15601.24402,6509.182054,...,2729.196041,4805.089800,41254.50524,5143.782954,1951.046760,8280.475759,567.470814,2939.733231,6945.056141,82019890.0
13,Germany,DEU,1996,4879.421622,5648.899141,1816.366622,19218.90113,847.429306,15460.33030,6564.281433,...,2705.160448,4923.434772,41589.46341,4986.808827,1994.038583,8417.152388,556.825092,3072.148396,7058.623038,NaN
14,Germany,DEU,1997,5018.973185,5682.366484,1789.692987,19024.63541,846.090500,15026.89728,6536.192025,...,2642.001978,5007.893275,41654.17138,4811.371950,2053.122612,8557.000130,543.938860,3186.577955,6954.382194,NaN
15,Germany,DEU,1998,5267.195405,5811.309260,1728.804693,18760.82886,849.329473,15070.75928,6412.480983,...,2549.859427,5207.192765,41516.10513,4941.767243,2104.080636,8772.796088,526.093612,3279.206331,6875.859234,NaN
16,Germany,DEU,1999,5434.287871,5823.306824,1706.500441,18616.54558,836.691553,14855.11490,6347.416730,...,2503.345760,5299.967549,41565.43048,4933.399296,2162.391232,8898.030766,514.775364,3333.464606,6832.940924,NaN
17,Germany,DEU,2000,5613.300987,5804.962474,1697.300860,18567.36217,822.298765,14593.68961,6275.411085,...,2469.539972,5362.451900,41670.89222,4880.038554,2237.053333,9028.552248,491.249548,3379.056587,6945.236395,81797258.0
18,Germany,DEU,2001,5775.909087,5805.131262,1665.418024,18504.57284,806.746567,14339.15452,6187.150777,...,2468.486016,5407.884365,41521.37757,4867.138666,2284.583300,9134.616885,472.232784,3423.486417,7004.601705,NaN
19,Germany,DEU,2002,5937.658440,5782.042802,1660.585546,18540.57877,792.760566,14165.21947,6140.133570,...,2444.201771,5444.585004,41730.19479,4804.267173,2339.472044,9192.687779,454.425262,3463.212396,7073.337575,NaN
20,Germany,DEU,2003,6143.642993,5794.616150,1649.540281,18481.97343,785.461158,13904.96934,6123.077422,...,2433.444248,5486.119054,42010.66206,4721.393790,2391.858641,9275.995970,445.919607,3493.167020,7184.711751,NaN
21,Germany,DEU,2004,6315.312612,5835.101040,1635.487807,18450.48851,772.985593,13665.19251,6113.376655,...,2429.589577,5512.557122,42267.21230,4649.716605,2441.480778,9373.034549,437.339770,3536.852807,7356.994199,NaN
22,Germany,DEU,2005,6510.191194,5921.127156,1633.842279,18589.27975,780.601524,13550.53091,6156.065933,...,2446.281082,5558.457172,42819.60270,4597.211110,2507.194058,9528.193109,434.211503,3587.383411,7574.252119,82046731.0
23,Germany,DEU,2006,6761.754437,6008.305967,1625.008395,18644.46060,785.049375,13351.72737,6217.232353,...,2463.327371,5589.143616,43246.56972,4548.525241,2570.609539,9633.441857,425.782796,3633.628426,7823.178528,NaN
24,Germany,DEU,2007,6947.605147,6098.190158,1608.830113,18666.74097,785.791773,13222.79102,6287.946774,...,2493.363071,5616.755366,43718.32711,4483.108422,2649.455390,9711.872139,417.627766,3686.370191,8067.833718,NaN
25,Germany,DEU,2008,7147.028027,6223.018750,1604.484733,18837.98433,797.529142,13072.45811,6366.677719,...,2524.757426,5663.479305,44289.93276,4443.360720,2741.661768,9799.766193,417.231334,3740.517911,8363.656059,NaN
26,Germany,DEU,2009,7336.253199,6343.508902,1594.223561,18923.71162,808.189639,13026.61898,6451.633093,...,2551.823008,5727.193372,44925.51113,4425.269112,2826.644601,9876.609410,415.327887,3799.704242,8675.644071,NaN
27,Germany,DEU,2010,7511.043379,6467.132063,1586.879650,18911.36382,818.234783,12983.57170,6587.807020,...,2588.056002,5772.186415,45468.41595,4424.296249,2896.909226,9915.087488,413.112449,3869.218443,9024.497896,80830924.0
28,Germany,DEU,2011,7645.233730,6592.646946,1577.292312,18849.00083,832.176477,12959.01716,6769.713575,...,2621.112661,5812.756802,45703.50642,4446.585891,2956.497028,9875.894371,411.106992,3930.879845,9463.950363,NaN
29,Germany,DEU,2012,7758.972017,6711.154048,1564.680238,18797.26131,847.964754,12985.60945,6906.156492,...,2653.951008,5864.108260,46063.62581,4473.403385,3008.956142,9890.949119,411.760173,3987.339428,9808.224214,NaN
30,Germany,DEU,2013,7846.717381,6836.387425,1564.721915,18774.86517,862.289837,12972.87044,7043.675081,...,2684.013225,5916.709077,46444.81032,4511.130553,3067.438682,9949.222558,409.360496,4054.026060,10086.648710,NaN
31,Germany,DEU,2014,7946.802085,6926.774727,1550.987239,18619.41778,863.366821,12871.27631,7149.755530,...,2702.548414,5983.262107,46407.73067,4527.216307,3102.645760,9962.849274,404.279128,4103.547804,10269.343220,NaN
32,Germany,DEU,2015,8040.209986,7062.175645,1549.620648,18615.36917,869.293248,13057.06670,7337.289187,...,2728.535250,6032.296143,46595.96113,4579.884648,3124.854494,10125.876920,403.995263,4180.160856,10252.073800,82077550.0
33,Germany,DEU,2016,8164.172707,7206.504844,1556.921490,18726.27221,878.868040,13254.25400,7531.119672,...,2762.572216,6103.834210,47003.50954,4647.629808,3165.783065,10288.294220,404.405435,4266.358908,10344.008880,NaN
34,NaN,NaN,2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,83628708.0
35,NaN,NaN,2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,84086227.0
36,NaN,NaN,2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,84548231.0
37,NaN,NaN,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,84552242.0
38,NaN,NaN,2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,84075075.0

In [476]:
# Delete rows in DF with "Country" = NaN
df_germany_cancer_population = df_germany_cancer_population.dropna(subset=["Country"])
df_germany_cancer_population

,Country,Code,Year,Liver cancer,Kidney cancer,Larynx cancer,Breast cancer,Thyroid cancer,Stomach cancer,Bladder cancer,...,Lip and oral cavity cancer,Brain and nervous system cancer,"Tracheal, bronchus, and lung cancer",Gallbladder and biliary tract cancer,Malignant skin melanoma,Leukemia,Hodgkin lymphoma,Multiple myeloma,Other cancers,Population
7,Germany,DEU,1990,3757.374920,5070.884825,1855.336341,18157.74796,887.084373,18064.03760,6554.166394,...,2587.833099,4167.556276,39108.93070,6247.529503,1876.667209,7857.333928,685.792368,2462.848310,6590.828644,79707959.0
8,Germany,DEU,1991,3806.755426,5175.336694,1863.910172,18357.45368,888.683344,17598.04676,6526.244891,...,2679.627435,4283.779982,39474.99723,6025.398918,1864.884273,7849.369655,668.733752,2540.582270,6615.596593,NaN
9,Germany,DEU,1992,4012.300112,5377.202082,1874.958860,18513.09420,876.688274,16985.78512,6457.869074,...,2754.463253,4443.287477,39892.78800,5849.096515,1902.643714,7877.700042,628.122778,2589.777272,6594.899118,NaN
10,Germany,DEU,1993,4226.851957,5477.157907,1866.609305,18717.06069,868.398282,16620.33808,6386.762284,...,2782.202128,4596.437998,40290.14965,5751.288806,1921.823275,7972.960424,605.466193,2691.958905,6579.922129,NaN
11,Germany,DEU,1994,4380.685176,5548.169025,1868.238055,18958.91876,856.514418,16087.02726,6353.730305,...,2737.170454,4693.452519,40657.80024,5523.457457,1923.332672,8153.135545,572.599272,2774.171419,6581.043743,NaN
12,Germany,DEU,1995,4691.199547,5595.011366,1856.012711,19128.57759,862.850826,15601.24402,6509.182054,...,2729.196041,4805.089800,41254.50524,5143.782954,1951.046760,8280.475759,567.470814,2939.733231,6945.056141,82019890.0
13,Germany,DEU,1996,4879.421622,5648.899141,1816.366622,19218.90113,847.429306,15460.33030,6564.281433,...,2705.160448,4923.434772,41589.46341,4986.808827,1994.038583,8417.152388,556.825092,3072.148396,7058.623038,NaN
14,Germany,DEU,1997,5018.973185,5682.366484,1789.692987,19024.63541,846.090500,15026.89728,6536.192025,...,2642.001978,5007.893275,41654.17138,4811.371950,2053.122612,8557.000130,543.938860,3186.577955,6954.382194,NaN
15,Germany,DEU,1998,5267.195405,5811.309260,1728.804693,18760.82886,849.329473,15070.75928,6412.480983,...,2549.859427,5207.192765,41516.10513,4941.767243,2104.080636,8772.796088,526.093612,3279.206331,6875.859234,NaN
16,Germany,DEU,1999,5434.287871,5823.306824,1706.500441,18616.54558,836.691553,14855.11490,6347.416730,...,2503.345760,5299.967549,41565.43048,4933.399296,2162.391232,8898.030766,514.775364,3333.464606,6832.940924,NaN
17,Germany,DEU,2000,5613.300987,5804.962474,1697.300860,18567.36217,822.298765,14593.68961,6275.411085,...,2469.539972,5362.451900,41670.89222,4880.038554,2237.053333,9028.552248,491.249548,3379.056587,6945.236395,81797258.0
18,Germany,DEU,2001,5775.909087,5805.131262,1665.418024,18504.57284,806.746567,14339.15452,6187.150777,...,2468.486016,5407.884365,41521.37757,4867.138666,2284.583300,9134.616885,472.232784,3423.486417,7004.601705,NaN
19,Germany,DEU,2002,5937.658440,5782.042802,1660.585546,18540.57877,792.760566,14165.21947,6140.133570,...,2444.201771,5444.585004,41730.19479,4804.267173,2339.472044,9192.687779,454.425262,3463.212396,7073.337575,NaN
20,Germany,DEU,2003,6143.642993,5794.616150,1649.540281,18481.97343,785.461158,13904.96934,6123.077422,...,2433.444248,5486.119054,42010.66206,4721.393790,2391.858641,9275.995970,445.919607,3493.167020,7184.711751,NaN
21,Germany,DEU,2004,6315.312612,5835.101040,1635.487807,18450.48851,772.985593,13665.19251,6113.376655,...,2429.589577,5512.557122,42267.21230,4649.716605,2441.480778,9373.034549,437.339770,3536.852807,7356.994199,NaN
22,Germany,DEU,2005,6510.191194,5921.127156,1633.842279,18589.27975,780.601524,13550.53091,6156.065933,...,2446.281082,5558.457172,42819.60270,4597.211110,2507.194058,9528.193109,434.211503,3587.383411,7574.252119,82046731.0
23,Germany,DEU,2006,6761.754437,6008.305967,1625.008395,18644.46060,785.049375,13351.72737,6217.232353,...,2463.327371,5589.143616,43246.56972,4548.525241,2570.609539,9633.441857,425.782796,3633.628426,7823.178528,NaN
24,Germany,DEU,2007,6947.605147,6098.190158,1608.830113,18666.74097,785.791773,13222.79102,6287.946774,...,2493.363071,5616.755366,43718.32711,4483.108422,2649.455390,9711.872139,417.627766,3686.370191,8067.833718,NaN
25,Germany,DEU,2008,7147.028027,6223.018750,1604.484733,18837.98433,797.529142,13072.45811,6366.677719,...,2524.757426,5663.479305,44289.93276,4443.360720,2741.661768,9799.766193,417.231334,3740.517911,8363.656059,NaN
26,Germany,DEU,2009,7336.253199,6343.508902,1594.223561,18923.71162,808.189639,13026.61898,6451.633093,...,2551.823008,5727.193372,44925.51113,4425.269112,2826.644601,9876.609410,415.327887,3799.704242,8675.644071,NaN
27,Germany,DEU,2010,7511.043379,6467.132063,1586.879650,18911.36382,818.234783,12983.57170,6587.807020,...,2588.056002,5772.186415,45468.41595,4424.296249,2896.909226,9915.087488,413.112449,3869.218443,9024.497896,80830924.0
28,Germany,DEU,2011,7645.233730,6592.646946,1577.292312,18849.00083,832.176477,12959.01716,6769.713575,...,2621.112661,5812.756802,45703.50642,4446.585891,2956.497028,9875.894371,411.106992,3930.879845,9463.950363,NaN
29,Germany,DEU,2012,7758.972017,6711.154048,1564.680238,18797.26131,847.964754,12985.60945,6906.156492,...,2653.951008,5864.108260,46063.62581,4473.403385,3008.956142,9890.949119,411.760173,3987.339428,9808.224214,NaN
30,Germany,DEU,2013,7846.717381,6836.387425,1564.721915,18774.86517,862.289837,12972.87044,7043.675081,...,2684.013225,5916.709077,46444.81032,4511.130553,3067.438682,9949.222558,409.360496,4054.026060,10086.648710,NaN
31,Germany,DEU,2014,7946.802085,6926.774727,1550.987239,18619.41778,863.366821,12871.27631,7149.755530,...,2702.548414,5983.262107,46407.73067,4527.216307,3102.645760,9962.849274,404.279128,4103.547804,10269.343220,NaN
32,Germany,DEU,2015,8040.209986,7062.175645,1549.620648,18615.36917,869.293248,13057.06670,7337.289187,...,2728.535250,6032.296143,46595.96113,4579.884648,3124.854494,10125.876920,403.995263,4180.160856,10252.073800,82077550.0
33,Germany,DEU,2016,8164.172707,7206.504844,1556.921490,18726.27221,878.868040,13254.25400,7531.119672,...,2762.572216,6103.834210,47003.50954,4647.629808,3165.783065,10288.294220,404.405435,4266.358908,10344.008880,NaN

In [477]:
# CLEANING AND ORGANIZING DATA FOR CHILE 
# We don´t need to add the Country to the Population lists, because we have separat Cancer Death DFs for Germany and Chile
# Create DFs from Population Data
df_chile_population = pd.DataFrame(population_data_chile)
df_chile_population

       0           1
0   2025  19,859,921
1   2024  19,764,771
2   2023  19,658,835
3   2022  19,553,036
4   2020  19,370,624
5   2015  18,047,625
6   2010  17,181,464
7   2005  16,348,778
8   2000  15,503,635
9   1995  14,527,381
10  1990  13,437,176
11  1985  12,395,274
12  1980  11,508,550
13  1975  10,671,559
14  1970   9,845,344
15  1965   9,012,938
16  1960   8,153,350
17  1955   7,332,301

In [478]:
# Naming the Columns with "Year" and "Population"
df_chile_population.rename(columns={0: "Year"}, inplace=True)
df_chile_population.rename(columns={1: "Population"}, inplace=True)
df_chile_population

    Year  Population
0   2025  19,859,921
1   2024  19,764,771
2   2023  19,658,835
3   2022  19,553,036
4   2020  19,370,624
5   2015  18,047,625
6   2010  17,181,464
7   2005  16,348,778
8   2000  15,503,635
9   1995  14,527,381
10  1990  13,437,176
11  1985  12,395,274
12  1980  11,508,550
13  1975  10,671,559
14  1970   9,845,344
15  1965   9,012,938
16  1960   8,153,350
17  1955   7,332,301

In [479]:
df_chile_population.dtypes

Year          object
Population    object
dtype: object

In [480]:
# Change Population DF data types into integers
df_chile_population["Year"] = df_chile_population["Year"].astype(int)
# The Population Count is a string containing comma, which need to be deleted first!
df_chile_population["Population"] = df_chile_population["Population"].str.replace(",", "").astype(int)
df_chile_population.dtypes

Year          int32
Population    int32
dtype: object

In [481]:
df_chile_population

    Year  Population
0   2025    19859921
1   2024    19764771
2   2023    19658835
3   2022    19553036
4   2020    19370624
5   2015    18047625
6   2010    17181464
7   2005    16348778
8   2000    15503635
9   1995    14527381
10  1990    13437176
11  1985    12395274
12  1980    11508550
13  1975    10671559
14  1970     9845344
15  1965     9012938
16  1960     8153350
17  1955     7332301

In [482]:
df_chile.dtypes

Country                                   object
Code                                      object
Year                                       int64
Liver cancer                             float64
Kidney cancer                            float64
Larynx cancer                            float64
Breast cancer                            float64
Thyroid cancer                           float64
Stomach cancer                           float64
Bladder cancer                           float64
Uterine cancer                           float64
Ovarian cancer                           float64
Cervical cancer                          float64
Prostate cancer                          float64
Pancreatic cancer                        float64
Esophageal cancer                        float64
Testicular cancer                        float64
Nasopharynx cancer                       float64
Other pharynx cancer                     float64
Colon and rectum cancer                  float64
Non-melanoma skin cancer                 float64
Lip and oral cavity cancer               float64
Brain and nervous system cancer          float64
Tracheal, bronchus, and lung cancer      float64
Gallbladder and biliary tract cancer     float64
Malignant skin melanoma                  float64
Leukemia                                 float64
Hodgkin lymphoma                         float64
Multiple myeloma                         float64
Other cancers                            float64
dtype: object

In [483]:
# Change Year format of Cancer Death tables into integer
df_chile["Year"] = df_chile["Year"].astype(int)
df_chile.dtypes

C:\Users\admin\AppData\Local\Temp\ipykernel_42272\2502164863.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_chile["Year"] = df_chile["Year"].astype(int)

Country                                   object
Code                                      object
Year                                       int32
Liver cancer                             float64
Kidney cancer                            float64
Larynx cancer                            float64
Breast cancer                            float64
Thyroid cancer                           float64
Stomach cancer                           float64
Bladder cancer                           float64
Uterine cancer                           float64
Ovarian cancer                           float64
Cervical cancer                          float64
Prostate cancer                          float64
Pancreatic cancer                        float64
Esophageal cancer                        float64
Testicular cancer                        float64
Nasopharynx cancer                       float64
Other pharynx cancer                     float64
Colon and rectum cancer                  float64
Non-melanoma skin cancer                 float64
Lip and oral cavity cancer               float64
Brain and nervous system cancer          float64
Tracheal, bronchus, and lung cancer      float64
Gallbladder and biliary tract cancer     float64
Malignant skin melanoma                  float64
Leukemia                                 float64
Hodgkin lymphoma                         float64
Multiple myeloma                         float64
Other cancers                            float64
dtype: object

In [484]:
# Concatenating Population tables with Cancer Death tables
df_chile_cancer_population = pd.merge(df_chile, df_chile_population, on='Year', how="outer")
df_chile_cancer_population

,Country,Code,Year,Liver cancer,Kidney cancer,Larynx cancer,Breast cancer,Thyroid cancer,Stomach cancer,Bladder cancer,...,Lip and oral cavity cancer,Brain and nervous system cancer,"Tracheal, bronchus, and lung cancer",Gallbladder and biliary tract cancer,Malignant skin melanoma,Leukemia,Hodgkin lymphoma,Multiple myeloma,Other cancers,Population
0,NaN,NaN,1955,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7332301.0
1,NaN,NaN,1960,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8153350.0
2,NaN,NaN,1965,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9012938.0
3,NaN,NaN,1970,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9845344.0
4,NaN,NaN,1975,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10671559.0
5,NaN,NaN,1980,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11508550.0
6,NaN,NaN,1985,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12395274.0
7,Chile,CHL,1990,532.876703,515.232673,133.827093,847.396590,73.041805,3134.143120,231.504649,...,97.755759,213.076623,1791.384215,1969.260915,86.360362,548.067010,72.092037,164.228294,841.473676,13437176.0
8,Chile,CHL,1991,538.671490,516.723079,127.096157,842.870478,71.927153,3037.340420,237.624048,...,96.833770,212.220945,1772.532782,1914.879890,89.495491,544.225825,68.474469,171.298548,844.897982,NaN
9,Chile,CHL,1992,550.046402,521.615500,125.099561,841.069976,71.678472,2985.138051,241.894555,...,95.906394,211.407955,1753.372730,1884.973832,91.514175,540.045619,65.201519,178.315691,851.708711,NaN
10,Chile,CHL,1993,573.266095,533.268435,127.160034,873.750546,73.735285,3033.882651,254.881965,...,99.475111,216.366704,1805.859907,1921.499409,95.744256,550.937871,64.514955,188.692394,873.900124,NaN
11,Chile,CHL,1994,599.583442,541.520721,131.898772,919.048631,76.151602,3133.928189,266.588986,...,102.524076,223.341981,1877.857200,1970.327303,103.256296,562.251949,64.816380,201.915411,901.161325,NaN
12,Chile,CHL,1995,629.832706,549.686609,137.807743,964.781056,78.760092,3255.131718,281.381457,...,106.830714,230.644809,1978.311832,2023.750352,111.151865,574.446572,65.904636,217.654852,931.451437,14527381.0
13,Chile,CHL,1996,653.748508,543.043405,134.010792,988.316988,79.669363,3293.899501,287.654178,...,104.644455,236.004203,2020.047316,2040.855200,114.852926,584.140899,65.187711,234.110597,956.583463,NaN
14,Chile,CHL,1997,681.261068,501.837536,132.498587,994.430098,78.871478,3323.835562,291.294429,...,108.965771,235.971600,1999.872366,2042.707270,120.541122,587.298965,64.395632,251.178648,980.854894,NaN
15,Chile,CHL,1998,697.114968,502.017821,129.933974,1030.017953,81.798451,3339.843451,300.588797,...,111.719466,246.634272,2006.471897,2062.470993,126.197274,595.337043,59.051350,268.754355,987.529719,NaN
16,Chile,CHL,1999,689.508117,493.266474,127.212286,1049.171344,85.192075,3400.745201,315.778881,...,115.319322,252.621391,2036.972494,2082.714763,131.351419,610.089218,60.686500,285.107723,1001.735165,NaN
17,Chile,CHL,2000,694.332425,493.237542,123.262410,1072.727907,87.619944,3409.301113,334.747082,...,119.855062,264.642073,2066.964390,2100.366819,136.903535,621.611160,56.041700,299.877786,1030.450715,15503635.0
18,Chile,CHL,2001,706.910144,501.680497,124.037231,1096.385514,89.440139,3436.119753,345.232125,...,120.794586,278.366447,2137.500797,2110.304707,138.373850,642.357210,55.682814,311.649048,1052.435984,NaN
19,Chile,CHL,2002,740.734806,514.331308,124.864042,1123.380780,93.130639,3497.592447,358.290859,...,123.290722,287.440866,2207.981475,2146.288461,142.986631,656.678106,56.082787,327.124145,1066.441714,NaN
20,Chile,CHL,2003,777.464309,528.214964,127.693700,1152.716822,96.087048,3546.167518,370.729141,...,125.898086,298.060754,2278.296846,2166.970245,148.797983,671.295526,54.890272,342.018749,1088.290957,NaN
21,Chile,CHL,2004,807.342306,553.481938,130.223832,1188.362166,96.457486,3578.684020,388.195901,...,129.496351,314.402296,2378.629264,2165.926582,151.687885,680.951908,56.596715,355.415350,1122.362504,NaN
22,Chile,CHL,2005,841.077847,577.238644,132.048868,1220.149235,97.805076,3579.942460,406.412628,...,130.829509,323.290565,2446.769868,2169.956992,152.100728,691.260234,54.188966,363.887991,1138.249306,16348778.0
23,Chile,CHL,2006,874.147854,586.734464,132.837489,1227.779486,99.652033,3562.311959,411.804897,...,134.035891,333.797379,2510.729569,2144.089951,153.250314,698.403737,54.778761,370.400489,1154.075692,NaN
24,Chile,CHL,2007,902.823384,602.781119,135.412662,1234.845267,102.395505,3541.004718,419.978624,...,137.562075,351.182188,2568.930565,2123.729968,154.071901,708.823906,53.566151,377.236309,1165.327516,NaN
25,Chile,CHL,2008,940.960525,623.652168,136.088919,1252.405624,102.789846,3553.188885,427.853489,...,140.222577,369.481695,2627.912742,2104.063827,154.961488,719.317325,53.312858,385.516200,1178.864956,NaN
26,Chile,CHL,2009,983.482151,652.472272,142.878291,1307.753629,108.527232,3680.861702,443.124426,...,145.170994,388.406837,2755.643607,2148.921971,159.435475,734.730602,54.453156,400.634062,1215.700905,NaN
27,Chile,CHL,2010,1027.755176,679.340779,146.718884,1355.631584,113.636203,3778.315993,465.419440,...,151.826480,405.804648,2893.613938,2189.469179,169.818345,755.114700,57.452671,416.223181,1253.328540,17181464.0
28,Chile,CHL,2011,1068.833695,703.535235,148.592511,1389.056614,114.328861,3789.974688,473.111820,...,160.450809,419.295887,2977.303319,2213.560589,175.084686,773.878202,58.189945,431.315217,1286.793185,NaN
29,Chile,CHL,2012,1118.124433,735.884294,151.581045,1425.894713,118.812314,3835.487320,483.744321,...,169.105846,430.185290,3070.337311,2238.158281,175.643744,795.621367,58.800908,447.414123,1321.677971,NaN
30,Chile,CHL,2013,1150.920440,759.334574,152.418107,1449.391506,122.586767,3858.277387,504.156666,...,174.222781,442.209361,3180.096998,2246.496939,180.269010,815.230858,60.652703,462.135052,1348.687244,NaN
31,Chile,CHL,2014,1190.102190,788.881915,155.403636,1461.112817,122.265797,3851.092663,529.283151,...,175.360635,450.610437,3231.479369,2250.518045,189.904679,823.594805,62.114782,475.355126,1362.428474,NaN
32,Chile,CHL,2015,1224.585997,811.959547,158.982017,1479.204915,124.450024,3934.473433,542.535154,...,182.079642,457.575883,3317.311168,2323.259961,195.254873,833.094265,61.368792,491.660304,1404.888451,18047625.0
33,Chile,CHL,2016,1265.944153,840.315118,163.967027,1510.971151,127.492652,4041.102792,562.622340,...,188.435663,467.583356,3430.442325,2397.526696,202.422867,849.478485,61.812656,510.180060,1447.229304,NaN
34,NaN,NaN,2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19370624.0
35,NaN,NaN,2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19553036.0
36,NaN,NaN,2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19658835.0
37,NaN,NaN,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19764771.0
38,NaN,NaN,2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19859921.0

In [485]:
# Delete rows in DF with "Country" = NaN
df_chile_cancer_population = df_chile_cancer_population.dropna(subset=["Country"])
df_chile_cancer_population

,Country,Code,Year,Liver cancer,Kidney cancer,Larynx cancer,Breast cancer,Thyroid cancer,Stomach cancer,Bladder cancer,...,Lip and oral cavity cancer,Brain and nervous system cancer,"Tracheal, bronchus, and lung cancer",Gallbladder and biliary tract cancer,Malignant skin melanoma,Leukemia,Hodgkin lymphoma,Multiple myeloma,Other cancers,Population
7,Chile,CHL,1990,532.876703,515.232673,133.827093,847.396590,73.041805,3134.143120,231.504649,...,97.755759,213.076623,1791.384215,1969.260915,86.360362,548.067010,72.092037,164.228294,841.473676,13437176.0
8,Chile,CHL,1991,538.671490,516.723079,127.096157,842.870478,71.927153,3037.340420,237.624048,...,96.833770,212.220945,1772.532782,1914.879890,89.495491,544.225825,68.474469,171.298548,844.897982,NaN
9,Chile,CHL,1992,550.046402,521.615500,125.099561,841.069976,71.678472,2985.138051,241.894555,...,95.906394,211.407955,1753.372730,1884.973832,91.514175,540.045619,65.201519,178.315691,851.708711,NaN
10,Chile,CHL,1993,573.266095,533.268435,127.160034,873.750546,73.735285,3033.882651,254.881965,...,99.475111,216.366704,1805.859907,1921.499409,95.744256,550.937871,64.514955,188.692394,873.900124,NaN
11,Chile,CHL,1994,599.583442,541.520721,131.898772,919.048631,76.151602,3133.928189,266.588986,...,102.524076,223.341981,1877.857200,1970.327303,103.256296,562.251949,64.816380,201.915411,901.161325,NaN
12,Chile,CHL,1995,629.832706,549.686609,137.807743,964.781056,78.760092,3255.131718,281.381457,...,106.830714,230.644809,1978.311832,2023.750352,111.151865,574.446572,65.904636,217.654852,931.451437,14527381.0
13,Chile,CHL,1996,653.748508,543.043405,134.010792,988.316988,79.669363,3293.899501,287.654178,...,104.644455,236.004203,2020.047316,2040.855200,114.852926,584.140899,65.187711,234.110597,956.583463,NaN
14,Chile,CHL,1997,681.261068,501.837536,132.498587,994.430098,78.871478,3323.835562,291.294429,...,108.965771,235.971600,1999.872366,2042.707270,120.541122,587.298965,64.395632,251.178648,980.854894,NaN
15,Chile,CHL,1998,697.114968,502.017821,129.933974,1030.017953,81.798451,3339.843451,300.588797,...,111.719466,246.634272,2006.471897,2062.470993,126.197274,595.337043,59.051350,268.754355,987.529719,NaN
16,Chile,CHL,1999,689.508117,493.266474,127.212286,1049.171344,85.192075,3400.745201,315.778881,...,115.319322,252.621391,2036.972494,2082.714763,131.351419,610.089218,60.686500,285.107723,1001.735165,NaN
17,Chile,CHL,2000,694.332425,493.237542,123.262410,1072.727907,87.619944,3409.301113,334.747082,...,119.855062,264.642073,2066.964390,2100.366819,136.903535,621.611160,56.041700,299.877786,1030.450715,15503635.0
18,Chile,CHL,2001,706.910144,501.680497,124.037231,1096.385514,89.440139,3436.119753,345.232125,...,120.794586,278.366447,2137.500797,2110.304707,138.373850,642.357210,55.682814,311.649048,1052.435984,NaN
19,Chile,CHL,2002,740.734806,514.331308,124.864042,1123.380780,93.130639,3497.592447,358.290859,...,123.290722,287.440866,2207.981475,2146.288461,142.986631,656.678106,56.082787,327.124145,1066.441714,NaN
20,Chile,CHL,2003,777.464309,528.214964,127.693700,1152.716822,96.087048,3546.167518,370.729141,...,125.898086,298.060754,2278.296846,2166.970245,148.797983,671.295526,54.890272,342.018749,1088.290957,NaN
21,Chile,CHL,2004,807.342306,553.481938,130.223832,1188.362166,96.457486,3578.684020,388.195901,...,129.496351,314.402296,2378.629264,2165.926582,151.687885,680.951908,56.596715,355.415350,1122.362504,NaN
22,Chile,CHL,2005,841.077847,577.238644,132.048868,1220.149235,97.805076,3579.942460,406.412628,...,130.829509,323.290565,2446.769868,2169.956992,152.100728,691.260234,54.188966,363.887991,1138.249306,16348778.0
23,Chile,CHL,2006,874.147854,586.734464,132.837489,1227.779486,99.652033,3562.311959,411.804897,...,134.035891,333.797379,2510.729569,2144.089951,153.250314,698.403737,54.778761,370.400489,1154.075692,NaN
24,Chile,CHL,2007,902.823384,602.781119,135.412662,1234.845267,102.395505,3541.004718,419.978624,...,137.562075,351.182188,2568.930565,2123.729968,154.071901,708.823906,53.566151,377.236309,1165.327516,NaN
25,Chile,CHL,2008,940.960525,623.652168,136.088919,1252.405624,102.789846,3553.188885,427.853489,...,140.222577,369.481695,2627.912742,2104.063827,154.961488,719.317325,53.312858,385.516200,1178.864956,NaN
26,Chile,CHL,2009,983.482151,652.472272,142.878291,1307.753629,108.527232,3680.861702,443.124426,...,145.170994,388.406837,2755.643607,2148.921971,159.435475,734.730602,54.453156,400.634062,1215.700905,NaN
27,Chile,CHL,2010,1027.755176,679.340779,146.718884,1355.631584,113.636203,3778.315993,465.419440,...,151.826480,405.804648,2893.613938,2189.469179,169.818345,755.114700,57.452671,416.223181,1253.328540,17181464.0
28,Chile,CHL,2011,1068.833695,703.535235,148.592511,1389.056614,114.328861,3789.974688,473.111820,...,160.450809,419.295887,2977.303319,2213.560589,175.084686,773.878202,58.189945,431.315217,1286.793185,NaN
29,Chile,CHL,2012,1118.124433,735.884294,151.581045,1425.894713,118.812314,3835.487320,483.744321,...,169.105846,430.185290,3070.337311,2238.158281,175.643744,795.621367,58.800908,447.414123,1321.677971,NaN
30,Chile,CHL,2013,1150.920440,759.334574,152.418107,1449.391506,122.586767,3858.277387,504.156666,...,174.222781,442.209361,3180.096998,2246.496939,180.269010,815.230858,60.652703,462.135052,1348.687244,NaN
31,Chile,CHL,2014,1190.102190,788.881915,155.403636,1461.112817,122.265797,3851.092663,529.283151,...,175.360635,450.610437,3231.479369,2250.518045,189.904679,823.594805,62.114782,475.355126,1362.428474,NaN
32,Chile,CHL,2015,1224.585997,811.959547,158.982017,1479.204915,124.450024,3934.473433,542.535154,...,182.079642,457.575883,3317.311168,2323.259961,195.254873,833.094265,61.368792,491.660304,1404.888451,18047625.0
33,Chile,CHL,2016,1265.944153,840.315118,163.967027,1510.971151,127.492652,4041.102792,562.622340,...,188.435663,467.583356,3430.442325,2397.526696,202.422867,849.478485,61.812656,510.180060,1447.229304,NaN

In [486]:
# Create a new DF with dropped "Population" = NaN
df_germany_cancer_population_5 = df_germany_cancer_population.dropna(subset=["Population"])
df_germany_cancer_population_5

,Country,Code,Year,Liver cancer,Kidney cancer,Larynx cancer,Breast cancer,Thyroid cancer,Stomach cancer,Bladder cancer,...,Lip and oral cavity cancer,Brain and nervous system cancer,"Tracheal, bronchus, and lung cancer",Gallbladder and biliary tract cancer,Malignant skin melanoma,Leukemia,Hodgkin lymphoma,Multiple myeloma,Other cancers,Population
7,Germany,DEU,1990,3757.374920,5070.884825,1855.336341,18157.74796,887.084373,18064.03760,6554.166394,...,2587.833099,4167.556276,39108.93070,6247.529503,1876.667209,7857.333928,685.792368,2462.848310,6590.828644,79707959.0
12,Germany,DEU,1995,4691.199547,5595.011366,1856.012711,19128.57759,862.850826,15601.24402,6509.182054,...,2729.196041,4805.089800,41254.50524,5143.782954,1951.046760,8280.475759,567.470814,2939.733231,6945.056141,82019890.0
17,Germany,DEU,2000,5613.300987,5804.962474,1697.300860,18567.36217,822.298765,14593.68961,6275.411085,...,2469.539972,5362.451900,41670.89222,4880.038554,2237.053333,9028.552248,491.249548,3379.056587,6945.236395,81797258.0
22,Germany,DEU,2005,6510.191194,5921.127156,1633.842279,18589.27975,780.601524,13550.53091,6156.065933,...,2446.281082,5558.457172,42819.60270,4597.211110,2507.194058,9528.193109,434.211503,3587.383411,7574.252119,82046731.0
27,Germany,DEU,2010,7511.043379,6467.132063,1586.879650,18911.36382,818.234783,12983.57170,6587.807020,...,2588.056002,5772.186415,45468.41595,4424.296249,2896.909226,9915.087488,413.112449,3869.218443,9024.497896,80830924.0
32,Germany,DEU,2015,8040.209986,7062.175645,1549.620648,18615.36917,869.293248,13057.06670,7337.289187,...,2728.535250,6032.296143,46595.96113,4579.884648,3124.854494,10125.876920,403.995263,4180.160856,10252.073800,82077550.0

In [487]:
# New DF with dropped "Population" = NaN
df_chile_cancer_population_5 = df_chile_cancer_population.dropna(subset=["Population"])
df_chile_cancer_population_5

,Country,Code,Year,Liver cancer,Kidney cancer,Larynx cancer,Breast cancer,Thyroid cancer,Stomach cancer,Bladder cancer,...,Lip and oral cavity cancer,Brain and nervous system cancer,"Tracheal, bronchus, and lung cancer",Gallbladder and biliary tract cancer,Malignant skin melanoma,Leukemia,Hodgkin lymphoma,Multiple myeloma,Other cancers,Population
7,Chile,CHL,1990,532.876703,515.232673,133.827093,847.396590,73.041805,3134.143120,231.504649,...,97.755759,213.076623,1791.384215,1969.260915,86.360362,548.067010,72.092037,164.228294,841.473676,13437176.0
12,Chile,CHL,1995,629.832706,549.686609,137.807743,964.781056,78.760092,3255.131718,281.381457,...,106.830714,230.644809,1978.311832,2023.750352,111.151865,574.446572,65.904636,217.654852,931.451437,14527381.0
17,Chile,CHL,2000,694.332425,493.237542,123.262410,1072.727907,87.619944,3409.301113,334.747082,...,119.855062,264.642073,2066.964390,2100.366819,136.903535,621.611160,56.041700,299.877786,1030.450715,15503635.0
22,Chile,CHL,2005,841.077847,577.238644,132.048868,1220.149235,97.805076,3579.942460,406.412628,...,130.829509,323.290565,2446.769868,2169.956992,152.100728,691.260234,54.188966,363.887991,1138.249306,16348778.0
27,Chile,CHL,2010,1027.755176,679.340779,146.718884,1355.631584,113.636203,3778.315993,465.419440,...,151.826480,405.804648,2893.613938,2189.469179,169.818345,755.114700,57.452671,416.223181,1253.328540,17181464.0
32,Chile,CHL,2015,1224.585997,811.959547,158.982017,1479.204915,124.450024,3934.473433,542.535154,...,182.079642,457.575883,3317.311168,2323.259961,195.254873,833.094265,61.368792,491.660304,1404.888451,18047625.0

In [488]:
df_germany_cancer_population_5.info

<bound method DataFrame.info of     Country Code  Year  Liver cancer   Kidney cancer   Larynx cancer   \
7   Germany  DEU  1990    3757.374920     5070.884825     1855.336341
12  Germany  DEU  1995    4691.199547     5595.011366     1856.012711
17  Germany  DEU  2000    5613.300987     5804.962474     1697.300860
22  Germany  DEU  2005    6510.191194     5921.127156     1633.842279
27  Germany  DEU  2010    7511.043379     6467.132063     1586.879650
32  Germany  DEU  2015    8040.209986     7062.175645     1549.620648

    Breast cancer   Thyroid cancer   Stomach cancer   Bladder cancer   ...  \
7      18157.74796       887.084373      18064.03760      6554.166394  ...
12     19128.57759       862.850826      15601.24402      6509.182054  ...
17     18567.36217       822.298765      14593.68961      6275.411085  ...
22     18589.27975       780.601524      13550.53091      6156.065933  ...
27     18911.36382       818.234783      12983.57170      6587.807020  ...
32     18615.36917       869.293248      13057.06670      7337.289187  ...

    Lip and oral cavity cancer   Brain and nervous system cancer   \
7                   2587.833099                       4167.556276
12                  2729.196041                       4805.089800
17                  2469.539972                       5362.451900
22                  2446.281082                       5558.457172
27                  2588.056002                       5772.186415
32                  2728.535250                       6032.296143

    Tracheal, bronchus, and lung cancer   \
7                            39108.93070
12                           41254.50524
17                           41670.89222
22                           42819.60270
27                           45468.41595
32                           46595.96113

    Gallbladder and biliary tract cancer   Malignant skin melanoma   \
7                             6247.529503               1876.667209
12                            5143.782954               1951.046760
17                            4880.038554               2237.053333
22                            4597.211110               2507.194058
27                            4424.296249               2896.909226
32                            4579.884648               3124.854494

       Leukemia   Hodgkin lymphoma   Multiple myeloma   Other cancers   \
7    7857.333928         685.792368        2462.848310     6590.828644
12   8280.475759         567.470814        2939.733231     6945.056141
17   9028.552248         491.249548        3379.056587     6945.236395
22   9528.193109         434.211503        3587.383411     7574.252119
27   9915.087488         413.112449        3869.218443     9024.497896
32  10125.876920         403.995263        4180.160856    10252.073800

    Population
7   79707959.0
12  82019890.0
17  81797258.0
22  82046731.0
27  80830924.0
32  82077550.0

[6 rows x 31 columns]>

In [489]:
print(df_germany_cancer_population_5.columns)

Index(['Country', 'Code', 'Year', 'Liver cancer ', 'Kidney cancer ',
       'Larynx cancer ', 'Breast cancer ', 'Thyroid cancer ',
       'Stomach cancer ', 'Bladder cancer ', 'Uterine cancer ',
       'Ovarian cancer ', 'Cervical cancer ', 'Prostate cancer ',
       'Pancreatic cancer ', 'Esophageal cancer ', 'Testicular cancer ',
       'Nasopharynx cancer ', 'Other pharynx cancer ',
       'Colon and rectum cancer ', 'Non-melanoma skin cancer ',
       'Lip and oral cavity cancer ', 'Brain and nervous system cancer ',
       'Tracheal, bronchus, and lung cancer ',
       'Gallbladder and biliary tract cancer ', 'Malignant skin melanoma ',
       'Leukemia ', 'Hodgkin lymphoma ', 'Multiple myeloma ', 'Other cancers ',
       'Population'],
      dtype='object')

In [504]:
# Creating two new DFs containing only information to answer hypotheses: cancer type of interest (breast & liver) vs. German population count and year. 

selected_columns_germany_breast = ["Country", "Year", "Population", "Breast cancer "]
df_germany_population_cancer_breast = df_germany_cancer_population_5[selected_columns_germany_breast]
df_germany_population_cancer_breast

    Country  Year  Population  Breast cancer
7   Germany  1990  79707959.0     18157.74796
12  Germany  1995  82019890.0     19128.57759
17  Germany  2000  81797258.0     18567.36217
22  Germany  2005  82046731.0     18589.27975
27  Germany  2010  80830924.0     18911.36382
32  Germany  2015  82077550.0     18615.36917

In [506]:
# Creating two new DFs containing only information to answer hypotheses: cancer type of interest (breast & liver) vs. German population count and year. 

selected_columns_germany_liver = ["Country", "Year", "Population", "Liver cancer "]
df_germany_population_cancer_liver = df_germany_cancer_population_5[selected_columns_germany_liver]
df_germany_population_cancer_liver

    Country  Year  Population  Liver cancer
7   Germany  1990  79707959.0    3757.374920
12  Germany  1995  82019890.0    4691.199547
17  Germany  2000  81797258.0    5613.300987
22  Germany  2005  82046731.0    6510.191194
27  Germany  2010  80830924.0    7511.043379
32  Germany  2015  82077550.0    8040.209986

In [508]:
# Resetting the indeces for easier statistics analyses - This does not work! Why ?
# df_germany_population_cancer_breast.set_index()
# df_germany_population_cancer_breast

In [510]:
# Resetting the indeces for easier statistics analyses - This does not work! Why ?
# df_germany_population_cancer_liver.set_index()
# df_germany_population_cancer_liver

In [512]:
# Calculating Statistics: % of cancer cases in population of that year. Add a new column with this info.
df_germany_population_cancer_breast["Cancer_Percentage"] = df_germany_population_cancer_breast["Breast cancer "]*100/df_germany_population_cancer_breast["Population"]
df_germany_population_cancer_breast

C:\Users\admin\AppData\Local\Temp\ipykernel_42272\3412791854.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_germany_population_cancer_breast["Cancer_Percentage"] = df_germany_population_cancer_breast["Breast cancer "]*100/df_germany_population_cancer_breast["Population"]

    Country  Year  Population  Breast cancer   Cancer_Percentage
7   Germany  1990  79707959.0     18157.74796           0.022780
12  Germany  1995  82019890.0     19128.57759           0.023322
17  Germany  2000  81797258.0     18567.36217           0.022699
22  Germany  2005  82046731.0     18589.27975           0.022657
27  Germany  2010  80830924.0     18911.36382           0.023396
32  Germany  2015  82077550.0     18615.36917           0.022680

In [514]:
# Calculating Statistics: increase rates of cancer & population.
df_germany_population_cancer_breast["Population_Increase"] = df_germany_population_cancer_breast["Population"].diff()
df_germany_population_cancer_breast["Breast_Cancer_Increase"] = df_germany_population_cancer_breast["Breast cancer "].diff()
df_germany_population_cancer_breast["Cancer_Percentage_Increase"] = df_germany_population_cancer_breast["Cancer_Percentage"].diff()
df_germany_population_cancer_breast

C:\Users\admin\AppData\Local\Temp\ipykernel_42272\1050947701.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_germany_population_cancer_breast["Population_Increase"] = df_germany_population_cancer_breast["Population"].diff()
C:\Users\admin\AppData\Local\Temp\ipykernel_42272\1050947701.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_germany_population_cancer_breast["Breast_Cancer_Increase"] = df_germany_population_cancer_breast["Breast cancer "].diff()
C:\Users\admin\AppData\Local\Temp\ipykernel_42272\1050947701.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_germany_population_cancer_breast["Cancer_Percentage_Increase"] = df_germany_population_cancer_breast["Cancer_Percentage"].diff()

,Country,Year,Population,Breast cancer,Cancer_Percentage,Population_Increase,Breast_Cancer_Increase,Cancer_Percentage_Increase
7,Germany,1990,79707959.0,18157.74796,0.022780,NaN,NaN,NaN
12,Germany,1995,82019890.0,19128.57759,0.023322,2311931.0,970.82963,0.000542
17,Germany,2000,81797258.0,18567.36217,0.022699,-222632.0,-561.21542,-0.000623
22,Germany,2005,82046731.0,18589.27975,0.022657,249473.0,21.91758,-0.000042
27,Germany,2010,80830924.0,18911.36382,0.023396,-1215807.0,322.08407,0.000739
32,Germany,2015,82077550.0,18615.36917,0.022680,1246626.0,-295.99465,-0.000716

In [516]:
# Calculating Statistics: % of cancer cases in population of that year. Add a new column with this info.
df_germany_population_cancer_liver["Cancer_Percentage"] = df_germany_population_cancer_liver["Liver cancer "]*100/df_germany_population_cancer_liver["Population"]
df_germany_population_cancer_liver

C:\Users\admin\AppData\Local\Temp\ipykernel_42272\2306027615.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_germany_population_cancer_liver["Cancer_Percentage"] = df_germany_population_cancer_liver["Liver cancer "]*100/df_germany_population_cancer_liver["Population"]

    Country  Year  Population  Liver cancer   Cancer_Percentage
7   Germany  1990  79707959.0    3757.374920           0.004714
12  Germany  1995  82019890.0    4691.199547           0.005720
17  Germany  2000  81797258.0    5613.300987           0.006862
22  Germany  2005  82046731.0    6510.191194           0.007935
27  Germany  2010  80830924.0    7511.043379           0.009292
32  Germany  2015  82077550.0    8040.209986           0.009796

In [518]:
# Calculating Statistics: increase rates of cancer & population.
df_germany_population_cancer_liver["Population_Increase"] = df_germany_population_cancer_liver["Population"].diff()
df_germany_population_cancer_liver["Liver_Cancer_Increase"] = df_germany_population_cancer_liver["Liver cancer "].diff()
df_germany_population_cancer_liver["Cancer_Percentage_Increase"] = df_germany_population_cancer_liver["Cancer_Percentage"].diff()
df_germany_population_cancer_liver

C:\Users\admin\AppData\Local\Temp\ipykernel_42272\3863375926.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_germany_population_cancer_liver["Population_Increase"] = df_germany_population_cancer_liver["Population"].diff()
C:\Users\admin\AppData\Local\Temp\ipykernel_42272\3863375926.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_germany_population_cancer_liver["Liver_Cancer_Increase"] = df_germany_population_cancer_liver["Liver cancer "].diff()
C:\Users\admin\AppData\Local\Temp\ipykernel_42272\3863375926.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_germany_population_cancer_liver["Cancer_Percentage_Increase"] = df_germany_population_cancer_liver["Cancer_Percentage"].diff()

,Country,Year,Population,Liver cancer,Cancer_Percentage,Population_Increase,Liver_Cancer_Increase,Cancer_Percentage_Increase
7,Germany,1990,79707959.0,3757.374920,0.004714,NaN,NaN,NaN
12,Germany,1995,82019890.0,4691.199547,0.005720,2311931.0,933.824627,0.001006
17,Germany,2000,81797258.0,5613.300987,0.006862,-222632.0,922.101440,0.001143
22,Germany,2005,82046731.0,6510.191194,0.007935,249473.0,896.890207,0.001072
27,Germany,2010,80830924.0,7511.043379,0.009292,-1215807.0,1000.852185,0.001358
32,Germany,2015,82077550.0,8040.209986,0.009796,1246626.0,529.166607,0.000504

In [520]:
# Total cancer incidences are increasing between 1990 and 2015 in Germany.
df_germany_cancer_population["total_cancer_cases"]=df_germany_cancer_population[[
    'Liver cancer ', 'Kidney cancer ', 'Larynx cancer ', 'Breast cancer ', 'Thyroid cancer ',
    'Stomach cancer ', 'Bladder cancer ', 'Uterine cancer ', 'Ovarian cancer ', 'Cervical cancer ',
    'Prostate cancer ', 'Pancreatic cancer ', 'Esophageal cancer ', 'Testicular cancer ',
    'Nasopharynx cancer ', 'Other pharynx cancer ', 'Colon and rectum cancer ', 'Non-melanoma skin cancer ',
    'Lip and oral cavity cancer ', 'Brain and nervous system cancer ', 'Tracheal, bronchus, and lung cancer ',
    'Gallbladder and biliary tract cancer ', 'Malignant skin melanoma ', 'Leukemia ', 'Hodgkin lymphoma ',
    'Multiple myeloma ', 'Other cancers ']].sum(axis=1)
df_germany_cancer_population

C:\Users\admin\AppData\Local\Temp\ipykernel_42272\742526786.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_germany_cancer_population["total_cancer_cases"]=df_germany_cancer_population[[

,Country,Code,Year,Liver cancer,Kidney cancer,Larynx cancer,Breast cancer,Thyroid cancer,Stomach cancer,Bladder cancer,...,Brain and nervous system cancer,"Tracheal, bronchus, and lung cancer",Gallbladder and biliary tract cancer,Malignant skin melanoma,Leukemia,Hodgkin lymphoma,Multiple myeloma,Other cancers,Population,total_cancer_cases
7,Germany,DEU,1990,3757.374920,5070.884825,1855.336341,18157.74796,887.084373,18064.03760,6554.166394,...,4167.556276,39108.93070,6247.529503,1876.667209,7857.333928,685.792368,2462.848310,6590.828644,79707959.0,195788.605203
8,Germany,DEU,1991,3806.755426,5175.336694,1863.910172,18357.45368,888.683344,17598.04676,6526.244891,...,4283.779982,39474.99723,6025.398918,1864.884273,7849.369655,668.733752,2540.582270,6615.596593,NaN,196579.635779
9,Germany,DEU,1992,4012.300112,5377.202082,1874.958860,18513.09420,876.688274,16985.78512,6457.869074,...,4443.287477,39892.78800,5849.096515,1902.643714,7877.700042,628.122778,2589.777272,6594.899118,NaN,197493.450791
10,Germany,DEU,1993,4226.851957,5477.157907,1866.609305,18717.06069,868.398282,16620.33808,6386.762284,...,4596.437998,40290.14965,5751.288806,1921.823275,7972.960424,605.466193,2691.958905,6579.922129,NaN,198918.049009
11,Germany,DEU,1994,4380.685176,5548.169025,1868.238055,18958.91876,856.514418,16087.02726,6353.730305,...,4693.452519,40657.80024,5523.457457,1923.332672,8153.135545,572.599272,2774.171419,6581.043743,NaN,199829.061942
12,Germany,DEU,1995,4691.199547,5595.011366,1856.012711,19128.57759,862.850826,15601.24402,6509.182054,...,4805.089800,41254.50524,5143.782954,1951.046760,8280.475759,567.470814,2939.733231,6945.056141,82019890.0,201416.841509
13,Germany,DEU,1996,4879.421622,5648.899141,1816.366622,19218.90113,847.429306,15460.33030,6564.281433,...,4923.434772,41589.46341,4986.808827,1994.038583,8417.152388,556.825092,3072.148396,7058.623038,NaN,202758.565348
14,Germany,DEU,1997,5018.973185,5682.366484,1789.692987,19024.63541,846.090500,15026.89728,6536.192025,...,5007.893275,41654.17138,4811.371950,2053.122612,8557.000130,543.938860,3186.577955,6954.382194,NaN,202145.349934
15,Germany,DEU,1998,5267.195405,5811.309260,1728.804693,18760.82886,849.329473,15070.75928,6412.480983,...,5207.192765,41516.10513,4941.767243,2104.080636,8772.796088,526.093612,3279.206331,6875.859234,NaN,202454.332701
16,Germany,DEU,1999,5434.287871,5823.306824,1706.500441,18616.54558,836.691553,14855.11490,6347.416730,...,5299.967549,41565.43048,4933.399296,2162.391232,8898.030766,514.775364,3333.464606,6832.940924,NaN,202589.123171
17,Germany,DEU,2000,5613.300987,5804.962474,1697.300860,18567.36217,822.298765,14593.68961,6275.411085,...,5362.451900,41670.89222,4880.038554,2237.053333,9028.552248,491.249548,3379.056587,6945.236395,81797258.0,203284.012509
18,Germany,DEU,2001,5775.909087,5805.131262,1665.418024,18504.57284,806.746567,14339.15452,6187.150777,...,5407.884365,41521.37757,4867.138666,2284.583300,9134.616885,472.232784,3423.486417,7004.601705,NaN,203401.305829
19,Germany,DEU,2002,5937.658440,5782.042802,1660.585546,18540.57877,792.760566,14165.21947,6140.133570,...,5444.585004,41730.19479,4804.267173,2339.472044,9192.687779,454.425262,3463.212396,7073.337575,NaN,203961.748868
20,Germany,DEU,2003,6143.642993,5794.616150,1649.540281,18481.97343,785.461158,13904.96934,6123.077422,...,5486.119054,42010.66206,4721.393790,2391.858641,9275.995970,445.919607,3493.167020,7184.711751,NaN,204403.260332
21,Germany,DEU,2004,6315.312612,5835.101040,1635.487807,18450.48851,772.985593,13665.19251,6113.376655,...,5512.557122,42267.21230,4649.716605,2441.480778,9373.034549,437.339770,3536.852807,7356.994199,NaN,204952.370405
22,Germany,DEU,2005,6510.191194,5921.127156,1633.842279,18589.27975,780.601524,13550.53091,6156.065933,...,5558.457172,42819.60270,4597.211110,2507.194058,9528.193109,434.211503,3587.383411,7574.252119,82046731.0,207086.160831
23,Germany,DEU,2006,6761.754437,6008.305967,1625.008395,18644.46060,785.049375,13351.72737,6217.232353,...,5589.143616,43246.56972,4548.525241,2570.609539,9633.441857,425.782796,3633.628426,7823.178528,NaN,208866.841596
24,Germany,DEU,2007,6947.605147,6098.190158,1608.830113,18666.74097,785.791773,13222.79102,6287.946774,...,5616.755366,43718.32711,4483.108422,2649.455390,9711.872139,417.627766,3686.370191,8067.833718,NaN,210508.582175
25,Germany,DEU,2008,7147.028027,6223.018750,1604.484733,18837.98433,797.529142,13072.45811,6366.677719,...,5663.479305,44289.93276,4443.360720,2741.661768,9799.766193,417.231334,3740.517911,8363.656059,NaN,212788.279246
26,Germany,DEU,2009,7336.253199,6343.508902,1594.223561,18923.71162,808.189639,13026.61898,6451.633093,...,5727.193372,44925.51113,4425.269112,2826.644601,9876.609410,415.327887,3799.704242,8675.644071,NaN,215299.963243
27,Germany,DEU,2010,7511.043379,6467.132063,1586.879650,18911.36382,818.234783,12983.57170,6587.807020,...,5772.186415,45468.41595,4424.296249,2896.909226,9915.087488,413.112449,3869.218443,9024.497896,80830924.0,217753.038521
28,Germany,DEU,2011,7645.233730,6592.646946,1577.292312,18849.00083,832.176477,12959.01716,6769.713575,...,5812.756802,45703.50642,4446.585891,2956.497028,9875.894371,411.106992,3930.879845,9463.950363,NaN,220026.627832
29,Germany,DEU,2012,7758.972017,6711.154048,1564.680238,18797.26131,847.964754,12985.60945,6906.156492,...,5864.108260,46063.62581,4473.403385,3008.956142,9890.949119,411.760173,3987.339428,9808.224214,NaN,222289.136887
30,Germany,DEU,2013,7846.717381,6836.387425,1564.721915,18774.86517,862.289837,12972.87044,7043.675081,...,5916.709077,46444.81032,4511.130553,3067.438682,9949.222558,409.360496,4054.026060,10086.648710,NaN,224527.129149
31,Germany,DEU,2014,7946.802085,6926.774727,1550.987239,18619.41778,863.366821,12871.27631,7149.755530,...,5983.262107,46407.73067,4527.216307,3102.645760,9962.849274,404.279128,4103.547804,10269.343220,NaN,225428.152816
32,Germany,DEU,2015,8040.209986,7062.175645,1549.620648,18615.36917,869.293248,13057.06670,7337.289187,...,6032.296143,46595.96113,4579.884648,3124.854494,10125.876920,403.995263,4180.160856,10252.073800,82077550.0,228054.654043
33,Germany,DEU,2016,8164.172707,7206.504844,1556.921490,18726.27221,878.868040,13254.25400,7531.119672,...,6103.834210,47003.50954,4647.629808,3165.783065,10288.294220,404.405435,4266.358908,10344.008880,NaN,231439.631487

In [522]:
# Total cancer incidences are increasing between 1990 and 2015 in Germany.
df_germany_cancer_population["total_cancer_incidence"]=df_germany_cancer_population["total_cancer_cases"]*100/df_germany_population_cancer_liver["Population"]
df_germany_cancer_population

C:\Users\admin\AppData\Local\Temp\ipykernel_42272\344391794.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_germany_cancer_population["total_cancer_incidence"]=df_germany_cancer_population["total_cancer_cases"]*100/df_germany_population_cancer_liver["Population"]

,Country,Code,Year,Liver cancer,Kidney cancer,Larynx cancer,Breast cancer,Thyroid cancer,Stomach cancer,Bladder cancer,...,"Tracheal, bronchus, and lung cancer",Gallbladder and biliary tract cancer,Malignant skin melanoma,Leukemia,Hodgkin lymphoma,Multiple myeloma,Other cancers,Population,total_cancer_cases,total_cancer_incidence
7,Germany,DEU,1990,3757.374920,5070.884825,1855.336341,18157.74796,887.084373,18064.03760,6554.166394,...,39108.93070,6247.529503,1876.667209,7857.333928,685.792368,2462.848310,6590.828644,79707959.0,195788.605203,0.245632
8,Germany,DEU,1991,3806.755426,5175.336694,1863.910172,18357.45368,888.683344,17598.04676,6526.244891,...,39474.99723,6025.398918,1864.884273,7849.369655,668.733752,2540.582270,6615.596593,NaN,196579.635779,NaN
9,Germany,DEU,1992,4012.300112,5377.202082,1874.958860,18513.09420,876.688274,16985.78512,6457.869074,...,39892.78800,5849.096515,1902.643714,7877.700042,628.122778,2589.777272,6594.899118,NaN,197493.450791,NaN
10,Germany,DEU,1993,4226.851957,5477.157907,1866.609305,18717.06069,868.398282,16620.33808,6386.762284,...,40290.14965,5751.288806,1921.823275,7972.960424,605.466193,2691.958905,6579.922129,NaN,198918.049009,NaN
11,Germany,DEU,1994,4380.685176,5548.169025,1868.238055,18958.91876,856.514418,16087.02726,6353.730305,...,40657.80024,5523.457457,1923.332672,8153.135545,572.599272,2774.171419,6581.043743,NaN,199829.061942,NaN
12,Germany,DEU,1995,4691.199547,5595.011366,1856.012711,19128.57759,862.850826,15601.24402,6509.182054,...,41254.50524,5143.782954,1951.046760,8280.475759,567.470814,2939.733231,6945.056141,82019890.0,201416.841509,0.245571
13,Germany,DEU,1996,4879.421622,5648.899141,1816.366622,19218.90113,847.429306,15460.33030,6564.281433,...,41589.46341,4986.808827,1994.038583,8417.152388,556.825092,3072.148396,7058.623038,NaN,202758.565348,NaN
14,Germany,DEU,1997,5018.973185,5682.366484,1789.692987,19024.63541,846.090500,15026.89728,6536.192025,...,41654.17138,4811.371950,2053.122612,8557.000130,543.938860,3186.577955,6954.382194,NaN,202145.349934,NaN
15,Germany,DEU,1998,5267.195405,5811.309260,1728.804693,18760.82886,849.329473,15070.75928,6412.480983,...,41516.10513,4941.767243,2104.080636,8772.796088,526.093612,3279.206331,6875.859234,NaN,202454.332701,NaN
16,Germany,DEU,1999,5434.287871,5823.306824,1706.500441,18616.54558,836.691553,14855.11490,6347.416730,...,41565.43048,4933.399296,2162.391232,8898.030766,514.775364,3333.464606,6832.940924,NaN,202589.123171,NaN
17,Germany,DEU,2000,5613.300987,5804.962474,1697.300860,18567.36217,822.298765,14593.68961,6275.411085,...,41670.89222,4880.038554,2237.053333,9028.552248,491.249548,3379.056587,6945.236395,81797258.0,203284.012509,0.248522
18,Germany,DEU,2001,5775.909087,5805.131262,1665.418024,18504.57284,806.746567,14339.15452,6187.150777,...,41521.37757,4867.138666,2284.583300,9134.616885,472.232784,3423.486417,7004.601705,NaN,203401.305829,NaN
19,Germany,DEU,2002,5937.658440,5782.042802,1660.585546,18540.57877,792.760566,14165.21947,6140.133570,...,41730.19479,4804.267173,2339.472044,9192.687779,454.425262,3463.212396,7073.337575,NaN,203961.748868,NaN
20,Germany,DEU,2003,6143.642993,5794.616150,1649.540281,18481.97343,785.461158,13904.96934,6123.077422,...,42010.66206,4721.393790,2391.858641,9275.995970,445.919607,3493.167020,7184.711751,NaN,204403.260332,NaN
21,Germany,DEU,2004,6315.312612,5835.101040,1635.487807,18450.48851,772.985593,13665.19251,6113.376655,...,42267.21230,4649.716605,2441.480778,9373.034549,437.339770,3536.852807,7356.994199,NaN,204952.370405,NaN
22,Germany,DEU,2005,6510.191194,5921.127156,1633.842279,18589.27975,780.601524,13550.53091,6156.065933,...,42819.60270,4597.211110,2507.194058,9528.193109,434.211503,3587.383411,7574.252119,82046731.0,207086.160831,0.252400
23,Germany,DEU,2006,6761.754437,6008.305967,1625.008395,18644.46060,785.049375,13351.72737,6217.232353,...,43246.56972,4548.525241,2570.609539,9633.441857,425.782796,3633.628426,7823.178528,NaN,208866.841596,NaN
24,Germany,DEU,2007,6947.605147,6098.190158,1608.830113,18666.74097,785.791773,13222.79102,6287.946774,...,43718.32711,4483.108422,2649.455390,9711.872139,417.627766,3686.370191,8067.833718,NaN,210508.582175,NaN
25,Germany,DEU,2008,7147.028027,6223.018750,1604.484733,18837.98433,797.529142,13072.45811,6366.677719,...,44289.93276,4443.360720,2741.661768,9799.766193,417.231334,3740.517911,8363.656059,NaN,212788.279246,NaN
26,Germany,DEU,2009,7336.253199,6343.508902,1594.223561,18923.71162,808.189639,13026.61898,6451.633093,...,44925.51113,4425.269112,2826.644601,9876.609410,415.327887,3799.704242,8675.644071,NaN,215299.963243,NaN
27,Germany,DEU,2010,7511.043379,6467.132063,1586.879650,18911.36382,818.234783,12983.57170,6587.807020,...,45468.41595,4424.296249,2896.909226,9915.087488,413.112449,3869.218443,9024.497896,80830924.0,217753.038521,0.269393
28,Germany,DEU,2011,7645.233730,6592.646946,1577.292312,18849.00083,832.176477,12959.01716,6769.713575,...,45703.50642,4446.585891,2956.497028,9875.894371,411.106992,3930.879845,9463.950363,NaN,220026.627832,NaN
29,Germany,DEU,2012,7758.972017,6711.154048,1564.680238,18797.26131,847.964754,12985.60945,6906.156492,...,46063.62581,4473.403385,3008.956142,9890.949119,411.760173,3987.339428,9808.224214,NaN,222289.136887,NaN
30,Germany,DEU,2013,7846.717381,6836.387425,1564.721915,18774.86517,862.289837,12972.87044,7043.675081,...,46444.81032,4511.130553,3067.438682,9949.222558,409.360496,4054.026060,10086.648710,NaN,224527.129149,NaN
31,Germany,DEU,2014,7946.802085,6926.774727,1550.987239,18619.41778,863.366821,12871.27631,7149.755530,...,46407.73067,4527.216307,3102.645760,9962.849274,404.279128,4103.547804,10269.343220,NaN,225428.152816,NaN
32,Germany,DEU,2015,8040.209986,7062.175645,1549.620648,18615.36917,869.293248,13057.06670,7337.289187,...,46595.96113,4579.884648,3124.854494,10125.876920,403.995263,4180.160856,10252.073800,82077550.0,228054.654043,0.277853
33,Germany,DEU,2016,8164.172707,7206.504844,1556.921490,18726.27221,878.868040,13254.25400,7531.119672,...,47003.50954,4647.629808,3165.783065,10288.294220,404.405435,4266.358908,10344.008880,NaN,231439.631487,NaN

In [524]:
# Create a new DF with dropped "Population" = NaN
df_germany_cancer_population_total_5 = df_germany_cancer_population.dropna(subset=["Population"])
df_germany_cancer_population_total_5

,Country,Code,Year,Liver cancer,Kidney cancer,Larynx cancer,Breast cancer,Thyroid cancer,Stomach cancer,Bladder cancer,...,"Tracheal, bronchus, and lung cancer",Gallbladder and biliary tract cancer,Malignant skin melanoma,Leukemia,Hodgkin lymphoma,Multiple myeloma,Other cancers,Population,total_cancer_cases,total_cancer_incidence
7,Germany,DEU,1990,3757.374920,5070.884825,1855.336341,18157.74796,887.084373,18064.03760,6554.166394,...,39108.93070,6247.529503,1876.667209,7857.333928,685.792368,2462.848310,6590.828644,79707959.0,195788.605203,0.245632
12,Germany,DEU,1995,4691.199547,5595.011366,1856.012711,19128.57759,862.850826,15601.24402,6509.182054,...,41254.50524,5143.782954,1951.046760,8280.475759,567.470814,2939.733231,6945.056141,82019890.0,201416.841509,0.245571
17,Germany,DEU,2000,5613.300987,5804.962474,1697.300860,18567.36217,822.298765,14593.68961,6275.411085,...,41670.89222,4880.038554,2237.053333,9028.552248,491.249548,3379.056587,6945.236395,81797258.0,203284.012509,0.248522
22,Germany,DEU,2005,6510.191194,5921.127156,1633.842279,18589.27975,780.601524,13550.53091,6156.065933,...,42819.60270,4597.211110,2507.194058,9528.193109,434.211503,3587.383411,7574.252119,82046731.0,207086.160831,0.252400
27,Germany,DEU,2010,7511.043379,6467.132063,1586.879650,18911.36382,818.234783,12983.57170,6587.807020,...,45468.41595,4424.296249,2896.909226,9915.087488,413.112449,3869.218443,9024.497896,80830924.0,217753.038521,0.269393
32,Germany,DEU,2015,8040.209986,7062.175645,1549.620648,18615.36917,869.293248,13057.06670,7337.289187,...,46595.96113,4579.884648,3124.854494,10125.876920,403.995263,4180.160856,10252.073800,82077550.0,228054.654043,0.277853

In [540]:
print(df_germany_cancer_population_total_5.columns)

AttributeError: 'NoneType' object has no attribute 'columns'

In [538]:
# Creating a new DF containing only information to answer hypotheses 3: total cancer cases vs. German population count and year. 

selected_columns_germany_total = ["Country", "Code", "Year", "Population", "total_cancer_cases", "total_cancer_incidence"]
df_germany_cancer_population_total_5_short = df_germany_cancer_population_total_5[selected_columns_germany_total]
df_germany_cancer_population_total_5_short

TypeError: 'NoneType' object is not subscriptable

In [ ]:
# Create graphs to illustrate the answers to the hypotheses.
import seaborn as sns